// SPDX-FileCopyrightText: (c) 2025 The drm-cxx Contributors
// SPDX-License-Identifier: MIT
//
// cluster_sim_vulkan — instrument-cluster sibling of `cluster_sim`,
// rendered entirely through Vulkan. Two DMA-BUF-exported VkImages
// scan out on the PRIMARY + OVERLAY planes (double-buffered, ping-
// ponged each frame to avoid the single-buffered tearing earlier
// iterations had). One render pass, three Vulkan graphics pipelines:
//
//   1. bg pipeline       — full-screen triangle + bg.vert/bg.frag,
//                          paints cluster_sim's radial gradient
//                          (center #101626, edge #02040A, radius
//                          max(w,h)*0.6).
//   2. textured pipeline — UV-mapped quad + textured.vert/textured.frag,
//                          samples a Blend2D-painted dial template
//                          (rim + face + ticks) uploaded once at
//                          startup, alpha-blended over the bg.
//   3. needle pipeline   — UV-mapped quad + needle.vert/needle.frag,
//                          SDF line segment with rounded caps + hub
//                          disc + fwidth-AA, premultiplied output.
//                          No descriptor set, no texture sample —
//                          pure shader math.
//
// Output is DRM_FORMAT_MOD_LINEAR ARGB8888, exported as a DMA-BUF, and
// wrapped in ExternalDmaBufSource. No CPU layer.
//
// CLI mirrors `cluster_sim`:
//   cluster_sim_vulkan [--seconds N] [--mode WxH[@Hz]] [/dev/dri/cardN]
//
// Build gate: this TU is built only when `vulkan` is on, Blend2D is
// available, AND glslangValidator is found (it compiles the bg shaders
// at configure-with-build time and writes SPIR-V into headers that
// `#include` below).

#include "../../common/open_output.hpp"

#include <drm-cxx/core/resources.hpp>
#include <drm-cxx/detail/format.hpp>
#include <drm-cxx/detail/span.hpp>
#include <drm-cxx/modeset/mode.hpp>
#include <drm-cxx/modeset/page_flip.hpp>
#include <drm-cxx/scene/buffer_source.hpp>
#include <drm-cxx/scene/dumb_buffer_source.hpp>
#include <drm-cxx/scene/external_dma_buf_source.hpp>
#include <drm-cxx/scene/layer_desc.hpp>
#include <drm-cxx/scene/layer_scene.hpp>

#include <drm_fourcc.h>
#include <drm_mode.h>
#include <vulkan/vulkan_core.h>
#include <xf86drmMode.h>

#include <algorithm>
#include <blend2d/core/api.h>
#include <blend2d/core/context.h>
#include <blend2d/core/font.h>
#include <blend2d/core/fontdefs.h>
#include <blend2d/core/fontface.h>
#include <blend2d/core/format.h>
#include <blend2d/core/glyphbuffer.h>
#include <blend2d/core/image.h>
#include <blend2d/core/path.h>
#include <blend2d/core/rgba.h>
#include <cmath>
#include <cstddef>
#include <memory>
#include <ratio>
#include <system_error>
#include <tuple>

// SPIR-V byte arrays generated by glslangValidator at build time.
// Build dir is on the include path via meson.
#include "bg_frag_spv.h"       // k_bg_frag_spv
#include "bg_vert_spv.h"       // k_bg_vert_spv
#include "dial_fx_frag_spv.h"  // k_dial_fx_frag_spv
#include "drm-cxx/detail/expected.hpp"
#include "needle_frag_spv.h"     // k_needle_frag_spv
#include "needle_vert_spv.h"     // k_needle_vert_spv
#include "tex_array_frag_spv.h"  // k_tex_array_frag_spv
#include "tex_array_vert_spv.h"  // k_tex_array_vert_spv
#include "textured_frag_spv.h"   // k_textured_frag_spv
#include "textured_vert_spv.h"   // k_textured_vert_spv

// Blend2D umbrella: <blend2d/blend2d.h> on most distros, <blend2d.h>
// in older drops; cover both like cluster_sim does.
#if __has_include(<blend2d/blend2d.h>)
#include <blend2d/blend2d.h>  // NOLINT(misc-include-cleaner)
#elif __has_include(<blend2d.h>)
#include <blend2d.h>  // NOLINT(misc-include-cleaner)
#else
#error "Blend2D headers not found; cluster_sim_vulkan needs Blend2D installed"
#endif

#include <array>
#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <optional>
#include <string>
#include <string_view>
#include <sys/stat.h>
#include <sys/sysmacros.h>
#include <unistd.h>
#include <utility>
#include <vector>

namespace {

constexpr int k_default_seconds = 30;
constexpr double k_pi = 3.141592653589793;
// Dial sweep matches cluster_sim's: 3π/4 at the bottom-left, 3π/2 wide.
constexpr double k_dial_start_angle = 3.0 * k_pi / 4.0;
constexpr double k_dial_sweep_angle = 3.0 * k_pi / 2.0;
constexpr double k_speedo_period_s = 6.0;
constexpr double k_tach_period_s = 4.0;

// Info-text geometry — matches cluster_sim's k_info_w / k_info_h /
// k_info_speed_max_kmh. Each layer in the info texture array is one
// pre-rendered "<speed> km/h" template; the runtime pushes the
// current speed as the layer index.
constexpr std::uint32_t k_info_w = 320U;
constexpr std::uint32_t k_info_h = 140U;
constexpr std::uint32_t k_info_speed_max_kmh = 240U;
constexpr std::uint32_t k_info_layer_count = k_info_speed_max_kmh + 1U;
constexpr float k_info_speed_font_px = 96.0F;
constexpr float k_info_unit_font_px = 22.0F;
constexpr std::uint32_t k_info_text_argb = 0xFFE6E8EEU;
constexpr std::uint32_t k_info_unit_argb = 0xFF7C8090U;

// Warning-cell geometry — matches cluster_sim. 4 cells along the
// bottom, each with a lit and dim variant (8 templates total).
constexpr std::uint32_t k_warn_w = 400U;
constexpr std::uint32_t k_warn_h = 80U;
constexpr int k_warn_count = 4;
constexpr std::uint32_t k_warn_layer_count = k_warn_count * 2;
constexpr float k_warn_glyph_font_px = 36.0F;
constexpr std::uint32_t k_warn_dim_argb = 0xFF14181FU;
constexpr std::uint32_t k_warn_glyph_dim_argb = 0xFF38404CU;
constexpr std::uint32_t k_warn_cell_radius = 12U;

struct WarningSpec {
  const char* glyph;
  std::uint32_t lit_argb;
  std::uint32_t glyph_lit_argb;
};
constexpr std::array<WarningSpec, k_warn_count> k_warn_specs{{
    {"!", 0xFFB02A1AU, 0xFFFFE0D0U},  // brake / generic alert (red)
    {"E", 0xFFD08A1FU, 0xFFFFEFC0U},  // engine (amber)
    {"O", 0xFFB02A1AU, 0xFFFFE0D0U},  // oil
    {"H", 0xFFD08A1FU, 0xFFFFEFC0U},  // high-beam (amber)
}};

struct Args {
  int seconds{k_default_seconds};
  std::optional<std::tuple<std::uint32_t, std::uint32_t, std::uint32_t>> mode_override;
};

// Signal handler needs file scope.
// NOLINTNEXTLINE(cppcoreguidelines-avoid-non-const-global-variables)
std::atomic<bool> g_quit{false};
void on_sigint(int /*signo*/) noexcept {
  g_quit.store(true, std::memory_order_relaxed);
}

[[nodiscard]] Args parse_args(int& argc, char**& argv) {
  Args a;
  int write = 1;
  for (int i = 1; i < argc; ++i) {
    const std::string_view arg{argv[i]};
    if (arg == "--seconds" && (i + 1) < argc) {
      a.seconds = std::atoi(argv[++i]);
    } else if (arg == "--mode" && (i + 1) < argc) {
      const std::string spec{argv[++i]};
      std::uint32_t w = 0;
      std::uint32_t h = 0;
      std::uint32_t hz = 0;
      const auto* end = spec.data() + spec.size();
      const auto* p = spec.data();
      auto consume = [&](std::uint32_t& out) {
        std::uint32_t v = 0;
        bool any = false;
        while (p < end && *p >= '0' && *p <= '9') {
          v = (v * 10U) + static_cast<std::uint32_t>(*p++ - '0');
          any = true;
        }
        if (any) {
          out = v;
        }
        return any;
      };
      if (consume(w) && p < end) {
        ++p;  // 'x'
        if (consume(h)) {
          if (p < end && *p == '@') {
            ++p;
            (void)consume(hz);
          }
          a.mode_override.emplace(w, h, hz);
        }
      }
    } else {
      argv[write++] = argv[i];
    }
  }
  argc = write;
  return a;
}

// Find the VkPhysicalDevice whose DRM major/minor matches the
// rendered-from KMS device. Cross-device dma-buf import works on some
// drivers but is non-portable.
[[nodiscard]] VkPhysicalDevice pick_physical_device(VkInstance instance, int drm_fd) {
  struct stat st{};
  if (fstat(drm_fd, &st) != 0) {
    return VK_NULL_HANDLE;
  }
  const unsigned int want_major = major(st.st_rdev);
  const unsigned int want_minor = minor(st.st_rdev);

  std::uint32_t count = 0;
  vkEnumeratePhysicalDevices(instance, &count, nullptr);
  if (count == 0) {
    return VK_NULL_HANDLE;
  }
  std::vector<VkPhysicalDevice> devices(count);
  vkEnumeratePhysicalDevices(instance, &count, devices.data());

  auto get_drm_props = reinterpret_cast<
      PFN_vkGetPhysicalDeviceProperties2>(  // NOLINT(cppcoreguidelines-pro-type-reinterpret-cast)
      vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceProperties2"));
  if (get_drm_props == nullptr) {
    return devices.front();
  }

  for (auto* pd : devices) {
    VkPhysicalDeviceDrmPropertiesEXT drm_props{};
    drm_props.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DRM_PROPERTIES_EXT;
    VkPhysicalDeviceProperties2 props2{};
    props2.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2;
    props2.pNext = &drm_props;
    get_drm_props(pd, &props2);
    if ((drm_props.hasPrimary != VK_FALSE && drm_props.primaryMajor == want_major &&
         drm_props.primaryMinor == want_minor) ||
        (drm_props.hasRender != VK_FALSE && drm_props.renderMajor == want_major &&
         drm_props.renderMinor == want_minor)) {
      return pd;
    }
  }
  return devices.front();
}

[[nodiscard]] std::uint32_t find_memory_type(VkPhysicalDevice pd, std::uint32_t type_bits,
                                             VkMemoryPropertyFlags flags) {
  VkPhysicalDeviceMemoryProperties mp{};
  vkGetPhysicalDeviceMemoryProperties(pd, &mp);
  const drm::span<const VkMemoryType> types{mp.memoryTypes, mp.memoryTypeCount};
  for (std::uint32_t i = 0; i < types.size(); ++i) {
    if (((type_bits >> i) & 1U) == 0U) {
      continue;
    }
    if ((types[i].propertyFlags & flags) == flags) {
      return i;
    }
  }
  return 0xFFFFFFFFU;
}

[[nodiscard]] double dial_norm_from_phase(double phase01) noexcept {
  return 0.5 * (1.0 - std::cos(2.0 * k_pi * phase01));
}

// Engine-revving curve for the tach: quadratic acceleration to
// redline through the first 85% of the period, then a quick snap
// back to idle over the last 15% — reads as "rev up, shift, drop."
// Distinct from the speedo's smooth cosine so the two dials never
// feel synchronized.
[[nodiscard]] double tach_revs_from_phase(double phase01) noexcept {
  double const wrapped = phase01 - std::floor(phase01);
  if (wrapped < 0.85) {
    double const t = wrapped / 0.85;
    return std::clamp(t * t, 0.0, 1.0);
  }
  double const t = (wrapped - 0.85) / 0.15;
  return std::clamp(1.0 - t, 0.0, 1.0);
}

// Self-test triangle sweep used during the first k_startup_sweep_s
// seconds after launch: 0 -> 1 -> 0 over the duration. Mimics the
// instrument-cluster "wake-up animation" real cars do.
constexpr double k_startup_sweep_s = 2.0;
[[nodiscard]] double startup_sweep_norm(double t_sec) noexcept {
  double const phase = std::clamp(t_sec / k_startup_sweep_s, 0.0, 1.0);
  return 1.0 - std::abs((phase * 2.0) - 1.0);
}

// Paint the static parts of a dial — rim + face + ticks — into a
// dial_size × dial_size buffer. Pixel format is PRGB32 (premultiplied
// BGRA bytes), which lines up with VK_FORMAT_B8G8R8A8_UNORM when the
// buffer is the source of a buffer-to-image copy. Geometry proportions
// mirror cluster_sim's paint_dial_template so the two examples agree.
// Caller hands in a tightly packed buffer (stride = dial_size * 4).
void paint_dial_template(std::uint8_t* pixels, std::uint32_t dial_size) noexcept {
  if (pixels == nullptr || dial_size == 0U) {
    return;
  }
  const auto stride_bytes = static_cast<intptr_t>(dial_size) * 4;
  BLImage canvas;
  if (canvas.create_from_data(static_cast<int>(dial_size), static_cast<int>(dial_size),
                              BL_FORMAT_PRGB32, pixels, stride_bytes, BL_DATA_ACCESS_RW, nullptr,
                              nullptr) != BL_SUCCESS) {
    return;
  }
  BLContext ctx(canvas);
  // alpha=0 background — the textured-quad pipeline alpha-blends, so
  // the bg gradient shows through the dial's four corners.
  ctx.set_comp_op(BL_COMP_OP_SRC_COPY);
  ctx.fill_all(BLRgba32(0x00000000U));
  ctx.set_comp_op(BL_COMP_OP_SRC_OVER);

  const auto size = static_cast<double>(dial_size);
  const double cx = size / 2.0;
  const double cy = size / 2.0;
  const double r_outer = size * 0.48;
  const double r_inner = size * 0.42;
  const double r_tick_outer = size * 0.46;
  const double r_tick_inner = size * 0.38;
  constexpr int k_major_ticks = 12;

  ctx.fill_circle(BLCircle(cx, cy, r_outer), BLRgba32(0xFF606870U));  // rim
  ctx.fill_circle(BLCircle(cx, cy, r_inner), BLRgba32(0xFF080C18U));  // face

  ctx.set_stroke_width(std::max(2.0, size * 0.004));
  ctx.set_stroke_caps(BL_STROKE_CAP_ROUND);
  for (int i = 0; i <= k_major_ticks; ++i) {
    const double t = static_cast<double>(i) / static_cast<double>(k_major_ticks);
    const double a = k_dial_start_angle + (t * k_dial_sweep_angle);
    const double x1 = cx + (r_tick_inner * std::cos(a));
    const double y1 = cy + (r_tick_inner * std::sin(a));
    const double x2 = cx + (r_tick_outer * std::cos(a));
    const double y2 = cy + (r_tick_outer * std::sin(a));
    ctx.stroke_line(BLPoint(x1, y1), BLPoint(x2, y2), BLRgba32(0xFFC0C8D0U));
  }
  ctx.end();
}

// Try a handful of well-known Linux font paths in priority order.
// Mirrors cluster_sim's load_default_font_face: returns
// BL_ERROR_FONT_NOT_INITIALIZED when none of the candidates exist on
// this host (callers fall back to shape-less output).
[[nodiscard]] BLResult load_default_font_face(BLFontFace& face) noexcept {
  static constexpr std::array<const char*, 10> k_candidates = {
      "/usr/share/fonts/dejavu-sans-fonts/DejaVuSans-Bold.ttf",
      "/usr/share/fonts/dejavu/DejaVuSans-Bold.ttf",
      "/usr/share/fonts/TTF/DejaVuSans-Bold.ttf",
      "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
      "/usr/share/fonts/liberation-sans-fonts/LiberationSans-Bold.ttf",
      "/usr/share/fonts/liberation-sans/LiberationSans-Bold.ttf",
      "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
      "/usr/share/fonts/google-noto/NotoSans-Bold.ttf",
      "/usr/share/fonts/noto/NotoSans-Bold.ttf",
      "/usr/share/fonts/TTF/Vera.ttf",
  };
  for (const char* path : k_candidates) {
    if (face.create_from_file(path) == BL_SUCCESS) {
      return BL_SUCCESS;
    }
  }
  return BL_ERROR_FONT_NOT_INITIALIZED;
}

void paint_centered_text(BLContext& ctx, BLFont& font, std::string_view text, double cx,
                         double cy_baseline, std::uint32_t argb) noexcept {
  if (text.empty()) {
    return;
  }
  BLGlyphBuffer gb;
  gb.set_utf8_text(text.data(), text.size());
  if (font.shape(gb) != BL_SUCCESS) {
    return;
  }
  BLTextMetrics tm{};
  if (font.get_text_metrics(gb, tm) != BL_SUCCESS) {
    return;
  }
  double const text_w = tm.bounding_box.x1 - tm.bounding_box.x0;
  double const x = cx - (text_w * 0.5) - tm.bounding_box.x0;
  ctx.fill_utf8_text(BLPoint(x, cy_baseline), font, text.data(), text.size(), BLRgba32(argb));
}

// Paint one layer of the info-text texture array: a k_info_w x k_info_h
// transparent buffer with the speed digit string + "km/h" label
// painted on top. Caller fills 241 such layers (speed_kmh = 0..240) at
// startup.
void paint_center_info_template(std::uint8_t* template_pixels, std::uint32_t speed_kmh,
                                const BLFontFace& font_face) noexcept {
  if (template_pixels == nullptr) {
    return;
  }
  BLImage canvas;
  if (canvas.create_from_data(
          static_cast<int>(k_info_w), static_cast<int>(k_info_h), BL_FORMAT_PRGB32, template_pixels,
          static_cast<intptr_t>(k_info_w) * 4, BL_DATA_ACCESS_RW, nullptr, nullptr) != BL_SUCCESS) {
    return;
  }
  BLContext ctx(canvas);
  ctx.set_comp_op(BL_COMP_OP_SRC_COPY);
  ctx.fill_all(BLRgba32(0x00000000U));
  if (!font_face.is_valid()) {
    ctx.end();
    return;
  }
  ctx.set_comp_op(BL_COMP_OP_SRC_OVER);
  std::string const speed_text = std::to_string(std::clamp<std::uint32_t>(speed_kmh, 0, 999));
  BLFont speed_font;
  if (speed_font.create_from_face(font_face, k_info_speed_font_px) == BL_SUCCESS) {
    paint_centered_text(ctx, speed_font, speed_text, static_cast<double>(k_info_w) * 0.5,
                        static_cast<double>(k_info_h) * 0.72, k_info_text_argb);
  }
  BLFont unit_font;
  if (unit_font.create_from_face(font_face, k_info_unit_font_px) == BL_SUCCESS) {
    paint_centered_text(ctx, unit_font, "km/h", static_cast<double>(k_info_w) * 0.5,
                        static_cast<double>(k_info_h) * 0.95, k_info_unit_argb);
  }
  ctx.end();
}

// Paint one layer of the warning-cell texture array: a rounded-rect
// cell with a centered glyph. Caller fills 2 * k_warn_count = 8
// layers at startup (per-cell lit + dim variants).
void paint_warning_cell_template(std::uint8_t* template_pixels, std::uint32_t cell_argb,
                                 std::uint32_t glyph_argb, std::string_view glyph,
                                 const BLFontFace& font_face) noexcept {
  if (template_pixels == nullptr) {
    return;
  }
  BLImage canvas;
  if (canvas.create_from_data(
          static_cast<int>(k_warn_w), static_cast<int>(k_warn_h), BL_FORMAT_PRGB32, template_pixels,
          static_cast<intptr_t>(k_warn_w) * 4, BL_DATA_ACCESS_RW, nullptr, nullptr) != BL_SUCCESS) {
    return;
  }
  BLContext ctx(canvas);
  ctx.set_comp_op(BL_COMP_OP_SRC_COPY);
  ctx.fill_all(BLRgba32(0x00000000U));
  ctx.set_comp_op(BL_COMP_OP_SRC_OVER);
  constexpr double k_inner_pad = 4.0;
  double const w = static_cast<double>(k_warn_w) - (2.0 * k_inner_pad);
  double const h = static_cast<double>(k_warn_h) - (2.0 * k_inner_pad);
  ctx.fill_round_rect(BLRoundRect(k_inner_pad, k_inner_pad, w, h, k_warn_cell_radius),
                      BLRgba32(cell_argb));
  BLFont glyph_font;
  if (font_face.is_valid() &&
      glyph_font.create_from_face(font_face, k_warn_glyph_font_px) == BL_SUCCESS) {
    double const cx = k_inner_pad + (w * 0.5);
    double const cy_baseline = k_inner_pad + (h * 0.7);
    paint_centered_text(ctx, glyph_font, std::string(glyph), cx, cy_baseline, glyph_argb);
  }
  ctx.end();
}

[[nodiscard]] VkShaderModule make_shader_module(VkDevice dev, const std::uint32_t* code,
                                                std::size_t code_bytes) {
  VkShaderModuleCreateInfo info{};
  info.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
  info.codeSize = code_bytes;
  info.pCode = code;
  VkShaderModule mod = VK_NULL_HANDLE;
  if (vkCreateShaderModule(dev, &info, nullptr, &mod) != VK_SUCCESS) {
    return VK_NULL_HANDLE;
  }
  return mod;
}

// Push-constant block for the bg fragment shader.
struct BgPushConstants {
  float extent_x;
  float extent_y;
};

// A LayerBufferSource that owns two ExternalDmaBufSource children and
// returns a different fb_id from acquire() per call, based on a
// front-buffer index the caller toggles. The scene holds ONE layer
// backed by this source; each commit's atomic page flip switches the
// PRIMARY plane between two FB IDs. That's classical front/back
// double-buffering at the kernel level, with no second hardware plane
// involved — important on Tegra where the OVERLAY plane's plane-alpha
// and dst_rect are unreliable knobs for hiding a buffer.
//
// The acquire/release lifecycle: the scene typically holds the
// AcquiredBuffer across the frame, sometimes across multiple frames
// (deferred-release ring). To make release route to the inner source
// the original acquire came from — even after the caller has flipped
// front_ since — we encode the inner source's index in
// AcquiredBuffer::opaque. ExternalDmaBufSource sets opaque=nullptr on
// acquire (verified in src/scene/external_dma_buf_source.cpp), so
// borrowing the field is safe.
class SwappingDmaBufSource : public drm::scene::LayerBufferSource {
 public:
  SwappingDmaBufSource(std::unique_ptr<drm::scene::ExternalDmaBufSource> a,
                       std::unique_ptr<drm::scene::ExternalDmaBufSource> b)
      : sources_{std::move(a), std::move(b)} {}

  [[nodiscard]] drm::expected<drm::scene::AcquiredBuffer, std::error_code> acquire()
      override {  // NOLINT(readability-make-member-function-const) — base is non-const.
    // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-constant-array-index)
    auto r = sources_[front_]->acquire();
    if (!r) {
      return r;
    }
    drm::scene::AcquiredBuffer buf = *r;
    // NOLINTNEXTLINE(performance-no-int-to-ptr,cppcoreguidelines-pro-type-reinterpret-cast)
    buf.opaque = reinterpret_cast<void*>(static_cast<std::uintptr_t>(front_));
    return buf;
  }

  void release(drm::scene::AcquiredBuffer acq) noexcept override {
    const auto idx = static_cast<std::size_t>(reinterpret_cast<std::uintptr_t>(
        acq.opaque));  // NOLINT(performance-no-int-to-ptr,cppcoreguidelines-pro-type-reinterpret-cast)
    if (idx < sources_.size()) {
      drm::scene::AcquiredBuffer const inner{acq.fb_id, nullptr};
      // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-constant-array-index)
      sources_[idx]->release(inner);
    }
  }

  [[nodiscard]] drm::scene::BindingModel binding_model() const noexcept override {
    return sources_[0]->binding_model();
  }

  [[nodiscard]] drm::scene::SourceFormat format() const noexcept override {
    return sources_[0]->format();
  }

  // map() inherits the base default (Function not implemented) — both
  // children also reject map(), and we don't need composition fallback.

  void set_front(int idx) noexcept {
    if (idx >= 0 && static_cast<std::size_t>(idx) < sources_.size()) {
      front_ = static_cast<std::size_t>(idx);
    }
  }

 private:
  std::array<std::unique_ptr<drm::scene::ExternalDmaBufSource>, 2> sources_;
  std::size_t front_{0};
};

// Push-constant block for the textured-quad vertex shader. dst is in
// NDC (x0, y0, x1, y1); uv is in [0, 1]. 32 bytes total — comfortably
// under the 128-byte minimum guaranteed by Vulkan.
struct TexturedPushConstants {
  float dst_x0;
  float dst_y0;
  float dst_x1;
  float dst_y1;
  float uv_x0;
  float uv_y0;
  float uv_x1;
  float uv_y1;
};

// Push-constant block for the SDF-needle pipeline. Same dst+uv as the
// textured pipeline plus a needle color and the animated state. 64
// bytes total. All radii / thicknesses are in the dial's normalized
// [-1, 1] frame (1.0 = half-dial-size); the fragment shader re-centers
// v_uv into that frame.
struct NeedlePushConstants {
  float dst_x0;
  float dst_y0;
  float dst_x1;
  float dst_y1;
  float uv_x0;
  float uv_y0;
  float uv_x1;
  float uv_y1;
  float needle_r;
  float needle_g;
  float needle_b;
  float needle_a;
  float angle;
  float r_needle;
  float r_hub;
  float half_thickness;
  float redline_intensity;  // 0..1; tach pushes >0 above ~80% sweep
};

// dial_fx pipeline push constants — same dst+uv as the textured
// pipeline (matches textured.vert) plus a fragment-only fx_params
// vec4 whose .x is the redline intensity. 48 bytes.
struct DialFxPushConstants {
  float dst_x0;
  float dst_y0;
  float dst_x1;
  float dst_y1;
  float uv_x0;
  float uv_y0;
  float uv_x1;
  float uv_y1;
  float fx_x;  // redline intensity 0..1
  float fx_y;
  float fx_z;
  float fx_w;
};

// Push-constant block for the sampler2DArray (info / warn) pipeline.
// dst + uv match the textured-quad pipeline; layer_info.x is the
// array layer the fragment shader samples. 48 bytes.
struct TexArrayPushConstants {
  float dst_x0;
  float dst_y0;
  float dst_x1;
  float dst_y1;
  float uv_x0;
  float uv_y0;
  float uv_x1;
  float uv_y1;
  std::int32_t layer;
  std::int32_t pad0;
  std::int32_t pad1;
  std::int32_t pad2;
};

// Pixel rectangle → NDC. Vulkan NDC y is +1 at the bottom and -1 at
// the top by default (matches gl_Position with no flip), so a pixel
// y of 0 (top of the framebuffer) maps to -1.
[[nodiscard]] TexturedPushConstants make_quad_pc(std::int32_t px, std::int32_t py, std::uint32_t pw,
                                                 std::uint32_t ph, std::uint32_t fb_w,
                                                 std::uint32_t fb_h) noexcept {
  const auto fw = static_cast<float>(fb_w);
  const auto fh = static_cast<float>(fb_h);
  const float x0 = ((static_cast<float>(px) / fw) * 2.0F) - 1.0F;
  const float y0 = ((static_cast<float>(py) / fh) * 2.0F) - 1.0F;
  const float x1 = ((static_cast<float>(px + static_cast<std::int32_t>(pw)) / fw) * 2.0F) - 1.0F;
  const float y1 = ((static_cast<float>(py + static_cast<std::int32_t>(ph)) / fh) * 2.0F) - 1.0F;
  return TexturedPushConstants{x0, y0, x1, y1, 0.0F, 0.0F, 1.0F, 1.0F};
}

}  // namespace

// NOLINTNEXTLINE(readability-function-size) — demo main, kept inline for readability.
int main(int argc, char* argv[]) {
  std::signal(SIGINT, on_sigint);
  std::signal(SIGTERM, on_sigint);

  const Args args = parse_args(argc, argv);

  auto out = drm::examples::open_and_pick_output(argc, argv);
  if (!out) {
    return EXIT_FAILURE;
  }
  auto& device = out->device;

  if (args.mode_override.has_value()) {
    const auto [tw, th, thz] = *args.mode_override;
    bool exact = false;
    auto conn = drm::get_connector(device.fd(), out->connector_id);
    if (conn) {
      auto picked = drm::select_mode(
          drm::span<const drmModeModeInfo>(conn->modes, conn->count_modes), tw, th, thz);
      if (picked) {
        const auto& m = picked->drm_mode;
        exact = (m.hdisplay == tw && m.vdisplay == th && (thz == 0 || m.vrefresh == thz));
        if (exact) {
          out->mode = m;
        }
      }
    }
    if (!exact) {
      // No exact match in the connector's EDID-derived mode list —
      // synthesize a CVT-RB2 (Coordinated Video Timings, Reduced
      // Blanking v2) modeline. Same fallback cluster_sim uses; the
      // kernel atomic ioctl accepts arbitrary drmModeModeInfo blobs.
      if (thz == 0) {
        drm::println(stderr, "--mode: no match for {}x{} and no refresh hint to synthesize from",
                     tw, th);
        return EXIT_FAILURE;
      }
      constexpr std::uint32_t k_h_blank_rb = 80;
      constexpr std::uint32_t k_h_front = 8;
      constexpr std::uint32_t k_h_sync = 32;
      constexpr std::uint32_t k_v_sync_rb = 8;
      constexpr std::uint32_t k_v_front_rb = 3;
      constexpr std::uint32_t k_v_back_rb_min = 6;
      std::uint32_t v_blank = 0;
      if (thz >= 200U) {
        v_blank = std::max<std::uint32_t>(80U, k_v_front_rb + k_v_sync_rb + k_v_back_rb_min);
      } else {
        v_blank = 32U;
        for (int it = 0; it < 8; ++it) {
          const double h_period_us =
              1.0e6 / (static_cast<double>(thz) * static_cast<double>(th + v_blank));
          const auto needed =
              static_cast<std::uint32_t>(std::lround(static_cast<double>(460U) / h_period_us));
          const std::uint32_t cand = std::max<std::uint32_t>(32U, needed);
          if (cand == v_blank) {
            break;
          }
          v_blank = cand;
        }
      }
      const std::uint32_t h_total = tw + k_h_blank_rb;
      const std::uint32_t v_total = th + v_blank;
      const std::uint64_t pclk_hz = static_cast<std::uint64_t>(thz) * h_total * v_total;
      const auto clock_khz = static_cast<std::uint32_t>((pclk_hz + 500U) / 1000U);
      drmModeModeInfo m{};
      m.clock = clock_khz;
      m.hdisplay = static_cast<std::uint16_t>(tw);
      m.hsync_start = static_cast<std::uint16_t>(tw + k_h_front);
      m.hsync_end = static_cast<std::uint16_t>(tw + k_h_front + k_h_sync);
      m.htotal = static_cast<std::uint16_t>(h_total);
      m.hskew = 0;
      m.vdisplay = static_cast<std::uint16_t>(th);
      m.vsync_start = static_cast<std::uint16_t>(th + k_v_front_rb);
      m.vsync_end = static_cast<std::uint16_t>(th + k_v_front_rb + k_v_sync_rb);
      m.vtotal = static_cast<std::uint16_t>(v_total);
      m.vscan = 0;
      m.vrefresh = thz;
      m.flags = DRM_MODE_FLAG_PHSYNC | DRM_MODE_FLAG_NVSYNC;
      m.type = DRM_MODE_TYPE_USERDEF;
      std::snprintf(m.name, DRM_DISPLAY_MODE_LEN, "%ux%u@%uRB", tw, th, thz);
      drm::println(stderr, "--mode: synthesized CVT-RB2 {}x{}@{}Hz pclk={}MHz htotal={} vtotal={}",
                   tw, th, thz, clock_khz / 1000U, h_total, v_total);
      out->mode = m;
    }
  }

  const std::uint32_t fb_w = out->mode.hdisplay;
  const std::uint32_t fb_h = out->mode.vdisplay;
  drm::println(stderr, "cluster_sim_vulkan: mode = {}x{}@{}Hz crtc={} connector={}", fb_w, fb_h,
               out->mode.vrefresh, out->crtc_id, out->connector_id);

  drm::scene::LayerScene::Config scene_cfg;
  scene_cfg.crtc_id = out->crtc_id;
  scene_cfg.connector_id = out->connector_id;
  scene_cfg.mode = out->mode;
  auto scene_r = drm::scene::LayerScene::create(device, scene_cfg);
  if (!scene_r) {
    drm::println(stderr, "LayerScene::create: {}", scene_r.error().message());
    return EXIT_FAILURE;
  }
  auto& scene = *scene_r;

  // Vulkan instance.
  const std::array<const char*, 2> inst_exts{
      "VK_KHR_get_physical_device_properties2",
      "VK_KHR_external_memory_capabilities",
  };
  VkApplicationInfo app{};
  app.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
  app.apiVersion = VK_API_VERSION_1_1;
  VkInstanceCreateInfo ici{};
  ici.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
  ici.pApplicationInfo = &app;
  ici.enabledExtensionCount = static_cast<std::uint32_t>(inst_exts.size());
  ici.ppEnabledExtensionNames = inst_exts.data();
  VkInstance instance = VK_NULL_HANDLE;
  if (vkCreateInstance(&ici, nullptr, &instance) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateInstance failed");
    return EXIT_FAILURE;
  }

  VkPhysicalDevice pd = pick_physical_device(instance, device.fd());
  if (pd == VK_NULL_HANDLE) {
    drm::println(stderr, "no VkPhysicalDevice matched the DRM fd");
    vkDestroyInstance(instance, nullptr);
    return EXIT_FAILURE;
  }

  std::uint32_t qf_count = 0;
  vkGetPhysicalDeviceQueueFamilyProperties(pd, &qf_count, nullptr);
  std::vector<VkQueueFamilyProperties> qfs(qf_count);
  vkGetPhysicalDeviceQueueFamilyProperties(pd, &qf_count, qfs.data());
  std::uint32_t qf_index = 0xFFFFFFFFU;
  for (std::uint32_t i = 0; i < qf_count; ++i) {
    if ((qfs[i].queueFlags & VK_QUEUE_GRAPHICS_BIT) != 0U) {
      qf_index = i;
      break;
    }
  }
  if (qf_index == 0xFFFFFFFFU) {
    drm::println(stderr, "no graphics queue");
    vkDestroyInstance(instance, nullptr);
    return EXIT_FAILURE;
  }

  const float qp = 1.0F;
  VkDeviceQueueCreateInfo qci{};
  qci.sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
  qci.queueFamilyIndex = qf_index;
  qci.queueCount = 1;
  qci.pQueuePriorities = &qp;
  const std::array<const char*, 5> dev_exts{
      "VK_KHR_external_memory",
      "VK_KHR_external_memory_fd",
      "VK_EXT_external_memory_dma_buf",
      "VK_EXT_image_drm_format_modifier",
      // Lets the end-of-frame barrier transfer queue-family ownership
      // of the DMA-BUF image to VK_QUEUE_FAMILY_FOREIGN_EXT (the KMS
      // scanout consumer), which on this Tegra driver is what
      // actually flushes the color-attachment writes out of the
      // GPU's cache so KMS sees them.
      "VK_EXT_queue_family_foreign",
  };
  VkDeviceCreateInfo dci{};
  dci.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
  dci.queueCreateInfoCount = 1;
  dci.pQueueCreateInfos = &qci;
  dci.enabledExtensionCount = static_cast<std::uint32_t>(dev_exts.size());
  dci.ppEnabledExtensionNames = dev_exts.data();
  VkDevice vk_device = VK_NULL_HANDLE;
  if (vkCreateDevice(pd, &dci, nullptr, &vk_device) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateDevice failed");
    vkDestroyInstance(instance, nullptr);
    return EXIT_FAILURE;
  }
  VkQueue queue = VK_NULL_HANDLE;
  vkGetDeviceQueue(vk_device, qf_index, 0, &queue);

  // Two DRM-modifier-LINEAR ARGB8888 Vulkan images, ping-ponged each
  // frame so KMS never reads the buffer Vulkan is currently writing.
  // Both DMA-BUFs are wrapped in one SwappingDmaBufSource, which is
  // attached to ONE scene layer on the PRIMARY plane. Each per-frame
  // commit page-flips that plane between the two FB IDs (front /
  // back), so KMS scans the just-rendered buffer while Vulkan renders
  // into the other one. Single plane — no OVERLAY tricks needed.
  constexpr int k_swap_count = 2;
  const std::uint64_t modifier = DRM_FORMAT_MOD_LINEAR;
  std::array<VkImage, k_swap_count> vk_images{};
  std::array<VkDeviceMemory, k_swap_count> vk_mems{};
  std::array<std::unique_ptr<drm::scene::ExternalDmaBufSource>, k_swap_count> bg_sources{};

  auto get_memory_fd = reinterpret_cast<
      PFN_vkGetMemoryFdKHR>(  // NOLINT(cppcoreguidelines-pro-type-reinterpret-cast)
      vkGetDeviceProcAddr(vk_device, "vkGetMemoryFdKHR"));
  if (get_memory_fd == nullptr) {
    drm::println(stderr, "vkGetMemoryFdKHR missing");
    return EXIT_FAILURE;
  }

  std::array<std::uint64_t, 1> modifiers{modifier};
  VkImageDrmFormatModifierListCreateInfoEXT drm_list{};
  drm_list.sType = VK_STRUCTURE_TYPE_IMAGE_DRM_FORMAT_MODIFIER_LIST_CREATE_INFO_EXT;
  drm_list.drmFormatModifierCount = 1;
  drm_list.pDrmFormatModifiers = modifiers.data();
  VkExternalMemoryImageCreateInfo ext_img{};
  ext_img.sType = VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO;
  ext_img.handleTypes = VK_EXTERNAL_MEMORY_HANDLE_TYPE_DMA_BUF_BIT_EXT;
  ext_img.pNext = &drm_list;

  for (int i = 0; i < k_swap_count; ++i) {
    VkImageCreateInfo iic{};
    iic.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
    iic.pNext = &ext_img;
    iic.imageType = VK_IMAGE_TYPE_2D;
    iic.format = VK_FORMAT_B8G8R8A8_UNORM;
    iic.extent = {fb_w, fb_h, 1};
    iic.mipLevels = 1;
    iic.arrayLayers = 1;
    iic.samples = VK_SAMPLE_COUNT_1_BIT;
    iic.tiling = VK_IMAGE_TILING_DRM_FORMAT_MODIFIER_EXT;
    iic.usage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT;
    iic.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    iic.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-constant-array-index)
    if (vkCreateImage(vk_device, &iic, nullptr, &vk_images[i]) != VK_SUCCESS) {
      drm::println(stderr, "vkCreateImage[{}] failed", i);
      return EXIT_FAILURE;
    }
    VkMemoryRequirements mr{};
    // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-constant-array-index)
    vkGetImageMemoryRequirements(vk_device, vk_images[i], &mr);
    VkExportMemoryAllocateInfo emai{};
    emai.sType = VK_STRUCTURE_TYPE_EXPORT_MEMORY_ALLOCATE_INFO;
    emai.handleTypes = VK_EXTERNAL_MEMORY_HANDLE_TYPE_DMA_BUF_BIT_EXT;
    VkMemoryAllocateInfo mai{};
    mai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    mai.pNext = &emai;
    mai.allocationSize = mr.size;
    mai.memoryTypeIndex =
        find_memory_type(pd, mr.memoryTypeBits, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (mai.memoryTypeIndex == 0xFFFFFFFFU) {
      drm::println(stderr, "no DEVICE_LOCAL memory type for bg image {}", i);
      return EXIT_FAILURE;
    }
    // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-constant-array-index)
    if (vkAllocateMemory(vk_device, &mai, nullptr, &vk_mems[i]) != VK_SUCCESS) {
      drm::println(stderr, "vkAllocateMemory[{}] failed", i);
      return EXIT_FAILURE;
    }
    // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-constant-array-index)
    vkBindImageMemory(vk_device, vk_images[i], vk_mems[i], 0);

    VkMemoryGetFdInfoKHR mgfi{};
    mgfi.sType = VK_STRUCTURE_TYPE_MEMORY_GET_FD_INFO_KHR;
    // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-constant-array-index)
    mgfi.memory = vk_mems[i];
    mgfi.handleType = VK_EXTERNAL_MEMORY_HANDLE_TYPE_DMA_BUF_BIT_EXT;
    int dmabuf_fd = -1;
    if (get_memory_fd(vk_device, &mgfi, &dmabuf_fd) != VK_SUCCESS || dmabuf_fd < 0) {
      drm::println(stderr, "vkGetMemoryFdKHR[{}] failed", i);
      return EXIT_FAILURE;
    }
    VkImageSubresource sub{};
    sub.aspectMask = VK_IMAGE_ASPECT_MEMORY_PLANE_0_BIT_EXT;
    VkSubresourceLayout layout{};
    // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-constant-array-index)
    vkGetImageSubresourceLayout(vk_device, vk_images[i], &sub, &layout);
    drm::scene::ExternalPlaneInfo plane_info{};
    plane_info.fd = dmabuf_fd;
    plane_info.pitch = static_cast<std::uint32_t>(layout.rowPitch);
    plane_info.offset = static_cast<std::uint32_t>(layout.offset);
    std::array<drm::scene::ExternalPlaneInfo, 1> planes{plane_info};
    auto src = drm::scene::ExternalDmaBufSource::create(device, fb_w, fb_h, DRM_FORMAT_ARGB8888,
                                                        modifier, planes);
    ::close(dmabuf_fd);
    if (!src) {
      drm::println(stderr, "ExternalDmaBufSource::create[{}]: {}", i, src.error().message());
      return EXIT_FAILURE;
    }
    // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-constant-array-index)
    bg_sources[i] = std::move(*src);
  }

  auto swap_source =
      std::make_unique<SwappingDmaBufSource>(std::move(bg_sources[0]), std::move(bg_sources[1]));
  auto* swap_source_raw = swap_source.get();
  drm::scene::LayerDesc bg_desc;
  bg_desc.source = std::move(swap_source);
  bg_desc.display.src_rect = drm::scene::Rect{0, 0, fb_w, fb_h};
  bg_desc.display.dst_rect = drm::scene::Rect{0, 0, fb_w, fb_h};
  bg_desc.display.zpos = 0;
  if (auto r = scene->add_layer(std::move(bg_desc)); !r) {
    drm::println(stderr, "add_layer (Vulkan bg): {}", r.error().message());
    return EXIT_FAILURE;
  }

  // Layout matches cluster_sim: dials capped at 400 px (or 4/9 of
  // fb_h, whichever is smaller), centered in their left/right halves;
  // the info readout floats in the middle column (overlapping the
  // dial centers vertically); the 4 warning cells sit 40 px below
  // the dials.
  const std::uint32_t dial_size = std::min<std::uint32_t>(fb_h * 4U / 9U, 400U);
  const auto dial_y = static_cast<std::int32_t>((fb_h - dial_size) / 2U);
  const std::int32_t speedo_x =
      static_cast<std::int32_t>(fb_w / 4U) - static_cast<std::int32_t>(dial_size / 2U);
  const std::int32_t tach_x =
      static_cast<std::int32_t>((fb_w * 3U) / 4U) - static_cast<std::int32_t>(dial_size / 2U);
  const std::int32_t info_x =
      static_cast<std::int32_t>(fb_w / 2U) - static_cast<std::int32_t>(k_info_w / 2U);
  const std::int32_t info_y =
      dial_y + static_cast<std::int32_t>(dial_size / 2U) - static_cast<std::int32_t>(k_info_h / 2U);
  const std::int32_t warn_strip_w = static_cast<std::int32_t>(k_warn_w) * k_warn_count;
  const std::int32_t warn_x0 = static_cast<std::int32_t>(fb_w / 2U) - (warn_strip_w / 2);
  const std::int32_t warn_y = dial_y + static_cast<std::int32_t>(dial_size) + 40;

  // -------- Vulkan render-pass plumbing (bg pipeline) -----------------
  // Single color attachment, format matches the image (B8G8R8A8_UNORM).
  // loadOp=DONT_CARE because the shader writes every pixel each frame.
  // finalLayout=GENERAL so KMS reads the post-render image without an
  // extra explicit barrier.
  VkAttachmentDescription attach{};
  attach.format = VK_FORMAT_B8G8R8A8_UNORM;
  attach.samples = VK_SAMPLE_COUNT_1_BIT;
  attach.loadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
  attach.storeOp = VK_ATTACHMENT_STORE_OP_STORE;
  attach.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
  attach.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
  attach.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
  attach.finalLayout = VK_IMAGE_LAYOUT_GENERAL;
  VkAttachmentReference color_ref{};
  color_ref.attachment = 0;
  color_ref.layout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
  // Two subpasses: bg writes the full attachment in subpass 0, then
  // the textured-quad pipeline reads-modifies-writes it in subpass 1.
  // Splitting the draws across subpasses with an explicit dependency
  // forces the bg's color-attachment writes to be visible to the
  // textured pipeline's blend reads — on this Tegra GPU's tile-based
  // rasterizer, a single subpass leaves a stale-read window at the
  // top of the dial.
  std::array<VkSubpassDescription, 2> subpasses{};
  subpasses[0].pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS;
  subpasses[0].colorAttachmentCount = 1;
  subpasses[0].pColorAttachments = &color_ref;
  subpasses[1].pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS;
  subpasses[1].colorAttachmentCount = 1;
  subpasses[1].pColorAttachments = &color_ref;
  std::array<VkSubpassDependency, 3> deps{};
  // External -> subpass 0: defer writes until the previous frame's
  // scanout reader has finished.
  deps[0].srcSubpass = VK_SUBPASS_EXTERNAL;
  deps[0].dstSubpass = 0;
  deps[0].srcStageMask = VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT;
  deps[0].dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
  deps[0].srcAccessMask = 0;
  deps[0].dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
  deps[0].dependencyFlags = 0;
  // Subpass 0 -> subpass 1: bg writes must be visible to textured's
  // blend reads. BY_REGION because the textured pipeline only reads
  // back the pixels it's about to write.
  deps[1].srcSubpass = 0;
  deps[1].dstSubpass = 1;
  deps[1].srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
  deps[1].dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
  deps[1].srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
  deps[1].dstAccessMask =
      VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
  deps[1].dependencyFlags = VK_DEPENDENCY_BY_REGION_BIT;
  // Subpass 1 -> external: release for the KMS scanout read.
  deps[2].srcSubpass = 1;
  deps[2].dstSubpass = VK_SUBPASS_EXTERNAL;
  deps[2].srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
  deps[2].dstStageMask = VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT;
  deps[2].srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
  deps[2].dstAccessMask = 0;
  deps[2].dependencyFlags = 0;
  VkRenderPassCreateInfo rpci{};
  rpci.sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
  rpci.attachmentCount = 1;
  rpci.pAttachments = &attach;
  rpci.subpassCount = static_cast<std::uint32_t>(subpasses.size());
  rpci.pSubpasses = subpasses.data();
  rpci.dependencyCount = static_cast<std::uint32_t>(deps.size());
  rpci.pDependencies = deps.data();
  VkRenderPass render_pass = VK_NULL_HANDLE;
  if (vkCreateRenderPass(vk_device, &rpci, nullptr, &render_pass) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateRenderPass failed");
    return EXIT_FAILURE;
  }

  std::array<VkImageView, k_swap_count> image_views{};
  std::array<VkFramebuffer, k_swap_count> framebuffers{};
  for (int i = 0; i < k_swap_count; ++i) {
    VkImageViewCreateInfo ivci{};
    ivci.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
    // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-constant-array-index)
    ivci.image = vk_images[i];
    ivci.viewType = VK_IMAGE_VIEW_TYPE_2D;
    ivci.format = VK_FORMAT_B8G8R8A8_UNORM;
    ivci.components = {VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY,
                       VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY};
    ivci.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
    // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-constant-array-index)
    if (vkCreateImageView(vk_device, &ivci, nullptr, &image_views[i]) != VK_SUCCESS) {
      drm::println(stderr, "vkCreateImageView[{}] failed", i);
      return EXIT_FAILURE;
    }
    VkFramebufferCreateInfo fbci{};
    fbci.sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO;
    fbci.renderPass = render_pass;
    fbci.attachmentCount = 1;
    // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-constant-array-index)
    fbci.pAttachments = &image_views[i];
    fbci.width = fb_w;
    fbci.height = fb_h;
    fbci.layers = 1;
    // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-constant-array-index)
    if (vkCreateFramebuffer(vk_device, &fbci, nullptr, &framebuffers[i]) != VK_SUCCESS) {
      drm::println(stderr, "vkCreateFramebuffer[{}] failed", i);
      return EXIT_FAILURE;
    }
  }

  // Shader modules.
  VkShaderModule bg_vert = make_shader_module(vk_device, k_bg_vert_spv, sizeof(k_bg_vert_spv));
  VkShaderModule bg_frag = make_shader_module(vk_device, k_bg_frag_spv, sizeof(k_bg_frag_spv));
  if (bg_vert == VK_NULL_HANDLE || bg_frag == VK_NULL_HANDLE) {
    drm::println(stderr, "vkCreateShaderModule failed");
    return EXIT_FAILURE;
  }

  // Pipeline layout: a single fragment-stage push constant (extent).
  VkPushConstantRange pcr{};
  pcr.stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;
  pcr.offset = 0;
  pcr.size = sizeof(BgPushConstants);
  VkPipelineLayoutCreateInfo plci{};
  plci.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
  plci.pushConstantRangeCount = 1;
  plci.pPushConstantRanges = &pcr;
  VkPipelineLayout pipeline_layout = VK_NULL_HANDLE;
  if (vkCreatePipelineLayout(vk_device, &plci, nullptr, &pipeline_layout) != VK_SUCCESS) {
    drm::println(stderr, "vkCreatePipelineLayout failed");
    return EXIT_FAILURE;
  }

  std::array<VkPipelineShaderStageCreateInfo, 2> stages{};
  stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
  stages[0].module = bg_vert;
  stages[0].pName = "main";
  stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
  stages[1].module = bg_frag;
  stages[1].pName = "main";

  VkPipelineVertexInputStateCreateInfo vi{};
  vi.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;

  VkPipelineInputAssemblyStateCreateInfo ia{};
  ia.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
  ia.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;

  VkViewport viewport{};
  viewport.x = 0.0F;
  viewport.y = 0.0F;
  viewport.width = static_cast<float>(fb_w);
  viewport.height = static_cast<float>(fb_h);
  viewport.minDepth = 0.0F;
  viewport.maxDepth = 1.0F;
  VkRect2D scissor{};
  scissor.offset = {0, 0};
  scissor.extent = {fb_w, fb_h};
  VkPipelineViewportStateCreateInfo vp{};
  vp.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
  vp.viewportCount = 1;
  vp.pViewports = &viewport;
  vp.scissorCount = 1;
  vp.pScissors = &scissor;

  VkPipelineRasterizationStateCreateInfo rs{};
  rs.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
  rs.polygonMode = VK_POLYGON_MODE_FILL;
  rs.cullMode = VK_CULL_MODE_NONE;
  rs.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE;
  rs.lineWidth = 1.0F;

  VkPipelineMultisampleStateCreateInfo ms{};
  ms.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
  ms.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

  VkPipelineColorBlendAttachmentState cba{};
  cba.blendEnable = VK_FALSE;
  cba.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
                       VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
  VkPipelineColorBlendStateCreateInfo cb{};
  cb.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
  cb.attachmentCount = 1;
  cb.pAttachments = &cba;

  VkGraphicsPipelineCreateInfo gpci{};
  gpci.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
  gpci.stageCount = static_cast<std::uint32_t>(stages.size());
  gpci.pStages = stages.data();
  gpci.pVertexInputState = &vi;
  gpci.pInputAssemblyState = &ia;
  gpci.pViewportState = &vp;
  gpci.pRasterizationState = &rs;
  gpci.pMultisampleState = &ms;
  gpci.pColorBlendState = &cb;
  gpci.layout = pipeline_layout;
  gpci.renderPass = render_pass;
  gpci.subpass = 0;
  VkPipeline pipeline = VK_NULL_HANDLE;
  if (vkCreateGraphicsPipelines(vk_device, VK_NULL_HANDLE, 1, &gpci, nullptr, &pipeline) !=
      VK_SUCCESS) {
    drm::println(stderr, "vkCreateGraphicsPipelines failed");
    return EXIT_FAILURE;
  }

  // Vulkan command pool + one re-recordable command buffer.
  VkCommandPoolCreateInfo pci{};
  pci.sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
  pci.queueFamilyIndex = qf_index;
  pci.flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
  VkCommandPool cmd_pool = VK_NULL_HANDLE;
  vkCreateCommandPool(vk_device, &pci, nullptr, &cmd_pool);
  VkCommandBufferAllocateInfo cbai{};
  cbai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
  cbai.commandPool = cmd_pool;
  cbai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
  cbai.commandBufferCount = 1;
  VkCommandBuffer cmd = VK_NULL_HANDLE;
  vkAllocateCommandBuffers(vk_device, &cbai, &cmd);

  // -------- Dial template texture + textured-quad pipeline ------------
  // One sampled image holds the static dial face (rim + face + ticks)
  // that Blend2D paints into a host-visible staging buffer at startup.
  // The textured-quad pipeline binds it as a combined image sampler and
  // alpha-blends over the bg gradient inside the same render pass.

  VkImageCreateInfo dial_ici{};
  dial_ici.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
  dial_ici.imageType = VK_IMAGE_TYPE_2D;
  dial_ici.format = VK_FORMAT_B8G8R8A8_UNORM;
  dial_ici.extent = {dial_size, dial_size, 1};
  dial_ici.mipLevels = 1;
  dial_ici.arrayLayers = 1;
  dial_ici.samples = VK_SAMPLE_COUNT_1_BIT;
  // LINEAR (not OPTIMAL) tiling for the dial template: the texture is
  // sampled once per fragment at 1:1 scale, so the tile-cache wins
  // from OPTIMAL are small, and OPTIMAL at non-power-of-2 widths
  // (e.g. 1440) on this Tegra driver appears to produce a dithered
  // band at the top of the dial. LINEAR's row-major layout
  // sidesteps it.
  dial_ici.tiling = VK_IMAGE_TILING_LINEAR;
  dial_ici.usage = VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT;
  dial_ici.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
  dial_ici.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
  VkImage dial_image = VK_NULL_HANDLE;
  if (vkCreateImage(vk_device, &dial_ici, nullptr, &dial_image) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateImage (dial) failed");
    return EXIT_FAILURE;
  }
  VkMemoryRequirements dial_mr{};
  vkGetImageMemoryRequirements(vk_device, dial_image, &dial_mr);
  VkMemoryAllocateInfo dial_mai{};
  dial_mai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
  dial_mai.allocationSize = dial_mr.size;
  dial_mai.memoryTypeIndex =
      find_memory_type(pd, dial_mr.memoryTypeBits, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
  VkDeviceMemory dial_mem = VK_NULL_HANDLE;
  if (vkAllocateMemory(vk_device, &dial_mai, nullptr, &dial_mem) != VK_SUCCESS) {
    drm::println(stderr, "vkAllocateMemory (dial) failed");
    return EXIT_FAILURE;
  }
  vkBindImageMemory(vk_device, dial_image, dial_mem, 0);

  // Staging buffer — host-visible coherent, sized for tightly packed
  // BGRA pixels. Blend2D paints into the mapped pointer.
  const VkDeviceSize dial_bytes = static_cast<VkDeviceSize>(dial_size) * dial_size * 4U;
  VkBufferCreateInfo dial_bci{};
  dial_bci.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
  dial_bci.size = dial_bytes;
  dial_bci.usage = VK_BUFFER_USAGE_TRANSFER_SRC_BIT;
  dial_bci.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
  VkBuffer staging_buf = VK_NULL_HANDLE;
  if (vkCreateBuffer(vk_device, &dial_bci, nullptr, &staging_buf) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateBuffer (staging) failed");
    return EXIT_FAILURE;
  }
  VkMemoryRequirements stg_mr{};
  vkGetBufferMemoryRequirements(vk_device, staging_buf, &stg_mr);
  VkMemoryAllocateInfo stg_mai{};
  stg_mai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
  stg_mai.allocationSize = stg_mr.size;
  stg_mai.memoryTypeIndex =
      find_memory_type(pd, stg_mr.memoryTypeBits,
                       VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
  VkDeviceMemory staging_mem = VK_NULL_HANDLE;
  if (vkAllocateMemory(vk_device, &stg_mai, nullptr, &staging_mem) != VK_SUCCESS) {
    drm::println(stderr, "vkAllocateMemory (staging) failed");
    return EXIT_FAILURE;
  }
  vkBindBufferMemory(vk_device, staging_buf, staging_mem, 0);

  void* stg_ptr = nullptr;
  vkMapMemory(vk_device, staging_mem, 0, dial_bytes, 0, &stg_ptr);
  // Defensive: vkAllocateMemory doesn't promise zero-init, and
  // Blend2D's fill_all + SRC_OVER drawing only writes pixels the
  // shapes touch — leaving anywhere outside the rim at whatever
  // residual values the allocator returned. Zero first.
  std::memset(stg_ptr, 0, static_cast<std::size_t>(dial_bytes));
  paint_dial_template(static_cast<std::uint8_t*>(stg_ptr), dial_size);
  vkUnmapMemory(vk_device, staging_mem);

  // One-shot upload command buffer: barrier UNDEFINED → TRANSFER_DST,
  // vkCmdCopyBufferToImage, barrier → SHADER_READ_ONLY_OPTIMAL.
  {
    VkCommandBufferBeginInfo upload_cbi{};
    upload_cbi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    upload_cbi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(cmd, &upload_cbi);

    VkImageMemoryBarrier to_dst{};
    to_dst.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
    to_dst.oldLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    to_dst.newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
    to_dst.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    to_dst.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    to_dst.image = dial_image;
    to_dst.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
    to_dst.srcAccessMask = 0;
    to_dst.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT, 0,
                         0, nullptr, 0, nullptr, 1, &to_dst);

    VkBufferImageCopy region{};
    region.bufferOffset = 0;
    region.bufferRowLength = 0;  // tightly packed
    region.bufferImageHeight = 0;
    region.imageSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
    region.imageOffset = {0, 0, 0};
    region.imageExtent = {dial_size, dial_size, 1};
    vkCmdCopyBufferToImage(cmd, staging_buf, dial_image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1,
                           &region);

    VkImageMemoryBarrier to_shader{};
    to_shader.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
    to_shader.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
    to_shader.newLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
    to_shader.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    to_shader.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    to_shader.image = dial_image;
    to_shader.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
    to_shader.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
    to_shader.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,
                         0, 0, nullptr, 0, nullptr, 1, &to_shader);

    vkEndCommandBuffer(cmd);

    VkSubmitInfo upload_si{};
    upload_si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    upload_si.commandBufferCount = 1;
    upload_si.pCommandBuffers = &cmd;
    vkQueueSubmit(queue, 1, &upload_si, VK_NULL_HANDLE);
    vkQueueWaitIdle(queue);
  }

  // Staging is done with — release it; the dial image owns its
  // contents on the device side now.
  vkDestroyBuffer(vk_device, staging_buf, nullptr);
  vkFreeMemory(vk_device, staging_mem, nullptr);

  VkImageViewCreateInfo dial_ivci{};
  dial_ivci.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
  dial_ivci.image = dial_image;
  dial_ivci.viewType = VK_IMAGE_VIEW_TYPE_2D;
  dial_ivci.format = VK_FORMAT_B8G8R8A8_UNORM;
  dial_ivci.components = {VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY,
                          VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY};
  dial_ivci.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
  VkImageView dial_view = VK_NULL_HANDLE;
  if (vkCreateImageView(vk_device, &dial_ivci, nullptr, &dial_view) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateImageView (dial) failed");
    return EXIT_FAILURE;
  }

  VkSamplerCreateInfo sci{};
  sci.sType = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO;
  sci.magFilter = VK_FILTER_LINEAR;
  sci.minFilter = VK_FILTER_LINEAR;
  sci.mipmapMode = VK_SAMPLER_MIPMAP_MODE_NEAREST;
  sci.addressModeU = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
  sci.addressModeV = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
  sci.addressModeW = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
  sci.minLod = 0.0F;
  sci.maxLod = 0.0F;
  sci.borderColor = VK_BORDER_COLOR_FLOAT_TRANSPARENT_BLACK;
  VkSampler dial_sampler = VK_NULL_HANDLE;
  if (vkCreateSampler(vk_device, &sci, nullptr, &dial_sampler) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateSampler failed");
    return EXIT_FAILURE;
  }

  VkDescriptorSetLayoutBinding dsb{};
  dsb.binding = 0;
  dsb.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
  dsb.descriptorCount = 1;
  dsb.stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;
  VkDescriptorSetLayoutCreateInfo dslci{};
  dslci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
  dslci.bindingCount = 1;
  dslci.pBindings = &dsb;
  VkDescriptorSetLayout dsl = VK_NULL_HANDLE;
  if (vkCreateDescriptorSetLayout(vk_device, &dslci, nullptr, &dsl) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateDescriptorSetLayout failed");
    return EXIT_FAILURE;
  }

  // Pool sized for three sets: dial (sampler2D), info-text array
  // (sampler2DArray, 241 layers), warn-cell array (sampler2DArray,
  // 8 layers). One combined-image-sampler descriptor per set.
  VkDescriptorPoolSize dps{};
  dps.type = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
  dps.descriptorCount = 3;
  VkDescriptorPoolCreateInfo dpci{};
  dpci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
  dpci.maxSets = 3;
  dpci.poolSizeCount = 1;
  dpci.pPoolSizes = &dps;
  VkDescriptorPool dpool = VK_NULL_HANDLE;
  if (vkCreateDescriptorPool(vk_device, &dpci, nullptr, &dpool) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateDescriptorPool failed");
    return EXIT_FAILURE;
  }
  VkDescriptorSetAllocateInfo dsai{};
  dsai.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
  dsai.descriptorPool = dpool;
  dsai.descriptorSetCount = 1;
  dsai.pSetLayouts = &dsl;
  VkDescriptorSet dset = VK_NULL_HANDLE;
  if (vkAllocateDescriptorSets(vk_device, &dsai, &dset) != VK_SUCCESS) {
    drm::println(stderr, "vkAllocateDescriptorSets failed");
    return EXIT_FAILURE;
  }
  VkDescriptorImageInfo dii{};
  dii.sampler = dial_sampler;
  dii.imageView = dial_view;
  dii.imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
  VkWriteDescriptorSet wds{};
  wds.sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
  wds.dstSet = dset;
  wds.dstBinding = 0;
  wds.descriptorCount = 1;
  wds.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
  wds.pImageInfo = &dii;
  vkUpdateDescriptorSets(vk_device, 1, &wds, 0, nullptr);

  // -------- Info-text + warn-cell texture arrays ---------------------
  // 241 info-text templates (0..240 km/h, k_info_w x k_info_h each) and
  // 8 warn-cell templates (4 cells x lit/dim, k_warn_w x k_warn_h each)
  // get Blend2D-painted into staging buffers and uploaded into two
  // 2D-array VkImages. A single shared sampler2DArray pipeline samples
  // both at runtime; the runtime pushes layer = current_speed_kmh for
  // the info quad and layer = cell*2 + lit ? 0 : 1 for each warn cell.

  BLFontFace font_face;
  if (load_default_font_face(font_face) != BL_SUCCESS) {
    drm::println(stderr,
                 "cluster_sim_vulkan: warning — no system font found, info/warn templates "
                 "will be blank rectangles");
  }

  auto make_array_image = [&](std::uint32_t w, std::uint32_t h, std::uint32_t layers, VkImage& img,
                              VkDeviceMemory& mem) -> bool {
    VkImageCreateInfo ici{};
    ici.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
    ici.imageType = VK_IMAGE_TYPE_2D;
    ici.format = VK_FORMAT_B8G8R8A8_UNORM;
    ici.extent = {w, h, 1};
    ici.mipLevels = 1;
    ici.arrayLayers = layers;
    ici.samples = VK_SAMPLE_COUNT_1_BIT;
    ici.tiling = VK_IMAGE_TILING_OPTIMAL;
    ici.usage = VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT;
    ici.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    ici.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    if (vkCreateImage(vk_device, &ici, nullptr, &img) != VK_SUCCESS) {
      return false;
    }
    VkMemoryRequirements mr{};
    vkGetImageMemoryRequirements(vk_device, img, &mr);
    VkMemoryAllocateInfo mai{};
    mai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    mai.allocationSize = mr.size;
    mai.memoryTypeIndex =
        find_memory_type(pd, mr.memoryTypeBits, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (vkAllocateMemory(vk_device, &mai, nullptr, &mem) != VK_SUCCESS) {
      return false;
    }
    vkBindImageMemory(vk_device, img, mem, 0);
    return true;
  };

  VkImage info_image = VK_NULL_HANDLE;
  VkDeviceMemory info_mem = VK_NULL_HANDLE;
  if (!make_array_image(k_info_w, k_info_h, k_info_layer_count, info_image, info_mem)) {
    drm::println(stderr, "info texture array create failed");
    return EXIT_FAILURE;
  }
  VkImage warn_image = VK_NULL_HANDLE;
  VkDeviceMemory warn_mem = VK_NULL_HANDLE;
  if (!make_array_image(k_warn_w, k_warn_h, k_warn_layer_count, warn_image, warn_mem)) {
    drm::println(stderr, "warn texture array create failed");
    return EXIT_FAILURE;
  }

  // Staging buffer big enough for the info array + warn array.
  // Layered images are tightly packed in staging: layer N's pixels
  // start at offset (info_bytes_per_layer * N), then warn array
  // follows the info data.
  const VkDeviceSize info_layer_bytes = static_cast<VkDeviceSize>(k_info_w) * k_info_h * 4U;
  const VkDeviceSize warn_layer_bytes = static_cast<VkDeviceSize>(k_warn_w) * k_warn_h * 4U;
  const VkDeviceSize info_bytes = info_layer_bytes * k_info_layer_count;
  const VkDeviceSize warn_bytes = warn_layer_bytes * k_warn_layer_count;
  const VkDeviceSize array_staging_bytes = info_bytes + warn_bytes;

  VkBufferCreateInfo astg_bci{};
  astg_bci.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
  astg_bci.size = array_staging_bytes;
  astg_bci.usage = VK_BUFFER_USAGE_TRANSFER_SRC_BIT;
  astg_bci.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
  VkBuffer array_staging_buf = VK_NULL_HANDLE;
  if (vkCreateBuffer(vk_device, &astg_bci, nullptr, &array_staging_buf) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateBuffer (info+warn staging) failed");
    return EXIT_FAILURE;
  }
  VkMemoryRequirements astg_mr{};
  vkGetBufferMemoryRequirements(vk_device, array_staging_buf, &astg_mr);
  VkMemoryAllocateInfo astg_mai{};
  astg_mai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
  astg_mai.allocationSize = astg_mr.size;
  astg_mai.memoryTypeIndex =
      find_memory_type(pd, astg_mr.memoryTypeBits,
                       VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
  VkDeviceMemory array_staging_mem = VK_NULL_HANDLE;
  if (vkAllocateMemory(vk_device, &astg_mai, nullptr, &array_staging_mem) != VK_SUCCESS) {
    drm::println(stderr, "vkAllocateMemory (info+warn staging) failed");
    return EXIT_FAILURE;
  }
  vkBindBufferMemory(vk_device, array_staging_buf, array_staging_mem, 0);

  void* astg_ptr = nullptr;
  vkMapMemory(vk_device, array_staging_mem, 0, array_staging_bytes, 0, &astg_ptr);
  std::memset(astg_ptr, 0, static_cast<std::size_t>(array_staging_bytes));
  // Info layers: speed_kmh = 0..240.
  for (std::uint32_t i = 0; i < k_info_layer_count; ++i) {
    auto* layer_ptr =
        static_cast<std::uint8_t*>(astg_ptr) + (static_cast<std::size_t>(info_layer_bytes) * i);
    paint_center_info_template(layer_ptr, i, font_face);
  }
  // Warn layers: per cell, lit first then dim.
  for (int cell = 0; cell < k_warn_count; ++cell) {
    // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-constant-array-index)
    const auto& spec = k_warn_specs[static_cast<std::size_t>(cell)];
    auto* lit_ptr =
        static_cast<std::uint8_t*>(astg_ptr) + static_cast<std::size_t>(info_bytes) +
        (static_cast<std::size_t>(warn_layer_bytes) * (static_cast<std::size_t>(cell * 2)));
    auto* dim_ptr = static_cast<std::uint8_t*>(astg_ptr) + static_cast<std::size_t>(info_bytes) +
                    (static_cast<std::size_t>(warn_layer_bytes) * ((cell * 2) + 1));
    paint_warning_cell_template(lit_ptr, spec.lit_argb, spec.glyph_lit_argb, spec.glyph, font_face);
    paint_warning_cell_template(dim_ptr, k_warn_dim_argb, k_warn_glyph_dim_argb, spec.glyph,
                                font_face);
  }
  vkUnmapMemory(vk_device, array_staging_mem);

  // One-shot upload command buffer for both arrays.
  {
    VkCommandBufferBeginInfo upload_cbi{};
    upload_cbi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    upload_cbi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(cmd, &upload_cbi);

    auto barrier_to = [&](VkImage img, std::uint32_t layers, VkImageLayout old_layout,
                          VkImageLayout new_layout, VkAccessFlags src_access,
                          VkAccessFlags dst_access, VkPipelineStageFlags src_stage,
                          VkPipelineStageFlags dst_stage) {
      VkImageMemoryBarrier b{};
      b.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
      b.oldLayout = old_layout;
      b.newLayout = new_layout;
      b.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
      b.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
      b.image = img;
      b.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, layers};
      b.srcAccessMask = src_access;
      b.dstAccessMask = dst_access;
      vkCmdPipelineBarrier(cmd, src_stage, dst_stage, 0, 0, nullptr, 0, nullptr, 1, &b);
    };

    barrier_to(info_image, k_info_layer_count, VK_IMAGE_LAYOUT_UNDEFINED,
               VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 0, VK_ACCESS_TRANSFER_WRITE_BIT,
               VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT);
    barrier_to(warn_image, k_warn_layer_count, VK_IMAGE_LAYOUT_UNDEFINED,
               VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 0, VK_ACCESS_TRANSFER_WRITE_BIT,
               VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT);

    std::vector<VkBufferImageCopy> info_regions(k_info_layer_count);
    for (std::uint32_t i = 0; i < k_info_layer_count; ++i) {
      info_regions[i].bufferOffset = info_layer_bytes * i;
      info_regions[i].imageSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, i, 1};
      info_regions[i].imageExtent = {k_info_w, k_info_h, 1};
    }
    vkCmdCopyBufferToImage(cmd, array_staging_buf, info_image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
                           static_cast<std::uint32_t>(info_regions.size()), info_regions.data());

    std::vector<VkBufferImageCopy> warn_regions(k_warn_layer_count);
    for (std::uint32_t i = 0; i < k_warn_layer_count; ++i) {
      warn_regions[i].bufferOffset = info_bytes + (warn_layer_bytes * i);
      warn_regions[i].imageSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, i, 1};
      warn_regions[i].imageExtent = {k_warn_w, k_warn_h, 1};
    }
    vkCmdCopyBufferToImage(cmd, array_staging_buf, warn_image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
                           static_cast<std::uint32_t>(warn_regions.size()), warn_regions.data());

    barrier_to(info_image, k_info_layer_count, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
               VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, VK_ACCESS_TRANSFER_WRITE_BIT,
               VK_ACCESS_SHADER_READ_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT,
               VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT);
    barrier_to(warn_image, k_warn_layer_count, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
               VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, VK_ACCESS_TRANSFER_WRITE_BIT,
               VK_ACCESS_SHADER_READ_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT,
               VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT);

    vkEndCommandBuffer(cmd);
    VkSubmitInfo si{};
    si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    si.commandBufferCount = 1;
    si.pCommandBuffers = &cmd;
    vkQueueSubmit(queue, 1, &si, VK_NULL_HANDLE);
    vkQueueWaitIdle(queue);
  }
  vkDestroyBuffer(vk_device, array_staging_buf, nullptr);
  vkFreeMemory(vk_device, array_staging_mem, nullptr);

  auto make_array_view = [&](VkImage img, std::uint32_t layers) -> VkImageView {
    VkImageViewCreateInfo ivci{};
    ivci.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
    ivci.image = img;
    ivci.viewType = VK_IMAGE_VIEW_TYPE_2D_ARRAY;
    ivci.format = VK_FORMAT_B8G8R8A8_UNORM;
    ivci.components = {VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY,
                       VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY};
    ivci.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, layers};
    VkImageView v = VK_NULL_HANDLE;
    if (vkCreateImageView(vk_device, &ivci, nullptr, &v) != VK_SUCCESS) {
      return VK_NULL_HANDLE;
    }
    return v;
  };
  VkImageView info_view = make_array_view(info_image, k_info_layer_count);
  VkImageView warn_view = make_array_view(warn_image, k_warn_layer_count);
  if (info_view == VK_NULL_HANDLE || warn_view == VK_NULL_HANDLE) {
    drm::println(stderr, "vkCreateImageView (info/warn array) failed");
    return EXIT_FAILURE;
  }

  // Allocate info + warn descriptor sets from the pool (the dial set
  // was allocated above; pool was sized for three sets total).
  auto alloc_array_set = [&](VkImageView view) -> VkDescriptorSet {
    VkDescriptorSetAllocateInfo a{};
    a.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
    a.descriptorPool = dpool;
    a.descriptorSetCount = 1;
    a.pSetLayouts = &dsl;
    VkDescriptorSet s = VK_NULL_HANDLE;
    if (vkAllocateDescriptorSets(vk_device, &a, &s) != VK_SUCCESS) {
      return VK_NULL_HANDLE;
    }
    VkDescriptorImageInfo dii_arr{};
    dii_arr.sampler = dial_sampler;
    dii_arr.imageView = view;
    dii_arr.imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
    VkWriteDescriptorSet w{};
    w.sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
    w.dstSet = s;
    w.dstBinding = 0;
    w.descriptorCount = 1;
    w.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
    w.pImageInfo = &dii_arr;
    vkUpdateDescriptorSets(vk_device, 1, &w, 0, nullptr);
    return s;
  };
  VkDescriptorSet info_dset = alloc_array_set(info_view);
  VkDescriptorSet warn_dset = alloc_array_set(warn_view);
  if (info_dset == VK_NULL_HANDLE || warn_dset == VK_NULL_HANDLE) {
    drm::println(stderr, "vkAllocateDescriptorSets (info/warn) failed");
    return EXIT_FAILURE;
  }

  // Textured shader modules.
  VkShaderModule tex_vert =
      make_shader_module(vk_device, k_textured_vert_spv, sizeof(k_textured_vert_spv));
  VkShaderModule tex_frag =
      make_shader_module(vk_device, k_textured_frag_spv, sizeof(k_textured_frag_spv));
  if (tex_vert == VK_NULL_HANDLE || tex_frag == VK_NULL_HANDLE) {
    drm::println(stderr, "vkCreateShaderModule (textured) failed");
    return EXIT_FAILURE;
  }

  // Textured pipeline layout: descriptor set + push constants.
  VkPushConstantRange tex_pcr{};
  tex_pcr.stageFlags = VK_SHADER_STAGE_VERTEX_BIT;
  tex_pcr.offset = 0;
  tex_pcr.size = sizeof(TexturedPushConstants);
  VkPipelineLayoutCreateInfo tex_plci{};
  tex_plci.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
  tex_plci.setLayoutCount = 1;
  tex_plci.pSetLayouts = &dsl;
  tex_plci.pushConstantRangeCount = 1;
  tex_plci.pPushConstantRanges = &tex_pcr;
  VkPipelineLayout tex_pipeline_layout = VK_NULL_HANDLE;
  if (vkCreatePipelineLayout(vk_device, &tex_plci, nullptr, &tex_pipeline_layout) != VK_SUCCESS) {
    drm::println(stderr, "vkCreatePipelineLayout (textured) failed");
    return EXIT_FAILURE;
  }

  std::array<VkPipelineShaderStageCreateInfo, 2> tex_stages{};
  tex_stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  tex_stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
  tex_stages[0].module = tex_vert;
  tex_stages[0].pName = "main";
  tex_stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  tex_stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
  tex_stages[1].module = tex_frag;
  tex_stages[1].pName = "main";

  // Premultiplied-alpha blend so the dial template's alpha-0 corners
  // let the bg gradient show through.
  VkPipelineColorBlendAttachmentState tex_cba{};
  tex_cba.blendEnable = VK_TRUE;
  tex_cba.srcColorBlendFactor = VK_BLEND_FACTOR_ONE;
  tex_cba.dstColorBlendFactor = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
  tex_cba.colorBlendOp = VK_BLEND_OP_ADD;
  tex_cba.srcAlphaBlendFactor = VK_BLEND_FACTOR_ONE;
  tex_cba.dstAlphaBlendFactor = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
  tex_cba.alphaBlendOp = VK_BLEND_OP_ADD;
  tex_cba.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
                           VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
  VkPipelineColorBlendStateCreateInfo tex_cb{};
  tex_cb.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
  tex_cb.attachmentCount = 1;
  tex_cb.pAttachments = &tex_cba;

  VkGraphicsPipelineCreateInfo tex_gpci{};
  tex_gpci.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
  tex_gpci.stageCount = static_cast<std::uint32_t>(tex_stages.size());
  tex_gpci.pStages = tex_stages.data();
  tex_gpci.pVertexInputState = &vi;    // empty, same as bg
  tex_gpci.pInputAssemblyState = &ia;  // triangle list
  tex_gpci.pViewportState = &vp;       // same fb-sized viewport
  tex_gpci.pRasterizationState = &rs;
  tex_gpci.pMultisampleState = &ms;
  tex_gpci.pColorBlendState = &tex_cb;
  tex_gpci.layout = tex_pipeline_layout;
  tex_gpci.renderPass = render_pass;
  tex_gpci.subpass = 1;
  VkPipeline tex_pipeline = VK_NULL_HANDLE;
  if (vkCreateGraphicsPipelines(vk_device, VK_NULL_HANDLE, 1, &tex_gpci, nullptr, &tex_pipeline) !=
      VK_SUCCESS) {
    drm::println(stderr, "vkCreateGraphicsPipelines (textured) failed");
    return EXIT_FAILURE;
  }

  // ----- Dial-fx pipeline (metallic rim highlight + top gloss) -----
  // Reuses textured.vert (push constants are dst + uv, no descriptor
  // set needed) plus a new fragment that draws shader-computed
  // highlights over the textured dial template.
  VkShaderModule dial_fx_frag =
      make_shader_module(vk_device, k_dial_fx_frag_spv, sizeof(k_dial_fx_frag_spv));
  if (dial_fx_frag == VK_NULL_HANDLE) {
    drm::println(stderr, "vkCreateShaderModule (dial_fx) failed");
    return EXIT_FAILURE;
  }
  VkPushConstantRange dfx_pcr{};
  dfx_pcr.stageFlags = VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT;
  dfx_pcr.offset = 0;
  dfx_pcr.size = sizeof(DialFxPushConstants);
  VkPipelineLayoutCreateInfo dfx_plci{};
  dfx_plci.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
  dfx_plci.pushConstantRangeCount = 1;
  dfx_plci.pPushConstantRanges = &dfx_pcr;
  VkPipelineLayout dial_fx_pipeline_layout = VK_NULL_HANDLE;
  if (vkCreatePipelineLayout(vk_device, &dfx_plci, nullptr, &dial_fx_pipeline_layout) !=
      VK_SUCCESS) {
    drm::println(stderr, "vkCreatePipelineLayout (dial_fx) failed");
    return EXIT_FAILURE;
  }
  std::array<VkPipelineShaderStageCreateInfo, 2> dfx_stages{};
  dfx_stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  dfx_stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
  dfx_stages[0].module = tex_vert;  // textured.vert handles dst+uv push
  dfx_stages[0].pName = "main";
  dfx_stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  dfx_stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
  dfx_stages[1].module = dial_fx_frag;
  dfx_stages[1].pName = "main";
  VkGraphicsPipelineCreateInfo dfx_gpci{};
  dfx_gpci.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
  dfx_gpci.stageCount = static_cast<std::uint32_t>(dfx_stages.size());
  dfx_gpci.pStages = dfx_stages.data();
  dfx_gpci.pVertexInputState = &vi;
  dfx_gpci.pInputAssemblyState = &ia;
  dfx_gpci.pViewportState = &vp;
  dfx_gpci.pRasterizationState = &rs;
  dfx_gpci.pMultisampleState = &ms;
  dfx_gpci.pColorBlendState = &tex_cb;  // premultiplied alpha
  dfx_gpci.layout = dial_fx_pipeline_layout;
  dfx_gpci.renderPass = render_pass;
  dfx_gpci.subpass = 1;
  VkPipeline dial_fx_pipeline = VK_NULL_HANDLE;
  if (vkCreateGraphicsPipelines(vk_device, VK_NULL_HANDLE, 1, &dfx_gpci, nullptr,
                                &dial_fx_pipeline) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateGraphicsPipelines (dial_fx) failed");
    return EXIT_FAILURE;
  }

  // Pre-computed push constants for the centered dial — the dst rect
  // doesn't change once the mode is locked.
  const TexturedPushConstants speedo_pc =
      make_quad_pc(speedo_x, dial_y, dial_size, dial_size, fb_w, fb_h);
  const TexturedPushConstants tach_pc =
      make_quad_pc(tach_x, dial_y, dial_size, dial_size, fb_w, fb_h);
  constexpr std::array<float, 4> k_speedo_needle_rgba{0xFF / 255.0F, 0x3B / 255.0F, 0x30 / 255.0F,
                                                      1.0F};  // cluster_sim 0xFFFF3B30
  constexpr std::array<float, 4> k_tach_needle_rgba{0xFF / 255.0F, 0xB3 / 255.0F, 0x00 / 255.0F,
                                                    1.0F};  // cluster_sim 0xFFFFB300

  // ----- Needle pipeline (SDF in fragment shader) -----------------
  // Same vertex geometry as the textured-quad pipeline. The
  // fragment shader resolves a line segment + hub disc analytically
  // and writes premultiplied alpha. No descriptor set — pure push-
  // constant + shader math.
  VkShaderModule needle_vert =
      make_shader_module(vk_device, k_needle_vert_spv, sizeof(k_needle_vert_spv));
  VkShaderModule needle_frag =
      make_shader_module(vk_device, k_needle_frag_spv, sizeof(k_needle_frag_spv));
  if (needle_vert == VK_NULL_HANDLE || needle_frag == VK_NULL_HANDLE) {
    drm::println(stderr, "vkCreateShaderModule (needle) failed");
    return EXIT_FAILURE;
  }
  VkPushConstantRange needle_pcr{};
  needle_pcr.stageFlags = VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT;
  needle_pcr.offset = 0;
  needle_pcr.size = sizeof(NeedlePushConstants);
  VkPipelineLayoutCreateInfo needle_plci{};
  needle_plci.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
  needle_plci.pushConstantRangeCount = 1;
  needle_plci.pPushConstantRanges = &needle_pcr;
  VkPipelineLayout needle_pipeline_layout = VK_NULL_HANDLE;
  if (vkCreatePipelineLayout(vk_device, &needle_plci, nullptr, &needle_pipeline_layout) !=
      VK_SUCCESS) {
    drm::println(stderr, "vkCreatePipelineLayout (needle) failed");
    return EXIT_FAILURE;
  }
  std::array<VkPipelineShaderStageCreateInfo, 2> needle_stages{};
  needle_stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  needle_stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
  needle_stages[0].module = needle_vert;
  needle_stages[0].pName = "main";
  needle_stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  needle_stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
  needle_stages[1].module = needle_frag;
  needle_stages[1].pName = "main";
  VkGraphicsPipelineCreateInfo needle_gpci{};
  needle_gpci.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
  needle_gpci.stageCount = static_cast<std::uint32_t>(needle_stages.size());
  needle_gpci.pStages = needle_stages.data();
  needle_gpci.pVertexInputState = &vi;    // empty
  needle_gpci.pInputAssemblyState = &ia;  // triangle list
  needle_gpci.pViewportState = &vp;       // full fb
  needle_gpci.pRasterizationState = &rs;
  needle_gpci.pMultisampleState = &ms;
  needle_gpci.pColorBlendState = &tex_cb;  // premultiplied alpha, same as textured
  needle_gpci.layout = needle_pipeline_layout;
  needle_gpci.renderPass = render_pass;
  needle_gpci.subpass = 1;
  VkPipeline needle_pipeline = VK_NULL_HANDLE;
  if (vkCreateGraphicsPipelines(vk_device, VK_NULL_HANDLE, 1, &needle_gpci, nullptr,
                                &needle_pipeline) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateGraphicsPipelines (needle) failed");
    return EXIT_FAILURE;
  }

  // Needle proportions in the dial's normalized [-1, 1] frame.
  // The dial template's r_outer (rim) is at 0.96 (=size*0.48 / (size/2));
  // r_needle = 0.40 / 0.50 = 0.80; r_hub = 0.06 / 0.50 = 0.12.
  // Half-thickness = 0.5 * 0.008 = 0.004 in the same frame — but the
  // fragment uses pre-doubled coords (the dial is 2 units across),
  // so feed half_thickness = (stroke_width/2) / (size/2) = 0.008/2 = 0.004
  // ... actually since paint_dial_template's stroke width was 11.52
  // pixels in a 1440-px dial, half-thickness in normalized [-1, 1]
  // (where 1.0 == 720 px) is (11.52/2) / 720 = 0.008.
  constexpr float k_r_needle_norm = 0.80F;
  constexpr float k_r_hub_norm = 0.12F;
  constexpr float k_half_thickness_norm = 0.008F;

  // ----- Texture-array pipeline (info text + warn cells) -----------
  // Single graphics pipeline; the runtime swaps which descriptor set
  // is bound (info vs warn) and pushes the layer index per draw.
  VkShaderModule tex_array_vert =
      make_shader_module(vk_device, k_tex_array_vert_spv, sizeof(k_tex_array_vert_spv));
  VkShaderModule tex_array_frag =
      make_shader_module(vk_device, k_tex_array_frag_spv, sizeof(k_tex_array_frag_spv));
  if (tex_array_vert == VK_NULL_HANDLE || tex_array_frag == VK_NULL_HANDLE) {
    drm::println(stderr, "vkCreateShaderModule (tex_array) failed");
    return EXIT_FAILURE;
  }
  VkPushConstantRange ta_pcr{};
  ta_pcr.stageFlags = VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT;
  ta_pcr.offset = 0;
  ta_pcr.size = sizeof(TexArrayPushConstants);
  VkPipelineLayoutCreateInfo ta_plci{};
  ta_plci.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
  ta_plci.setLayoutCount = 1;
  ta_plci.pSetLayouts = &dsl;
  ta_plci.pushConstantRangeCount = 1;
  ta_plci.pPushConstantRanges = &ta_pcr;
  VkPipelineLayout tex_array_pipeline_layout = VK_NULL_HANDLE;
  if (vkCreatePipelineLayout(vk_device, &ta_plci, nullptr, &tex_array_pipeline_layout) !=
      VK_SUCCESS) {
    drm::println(stderr, "vkCreatePipelineLayout (tex_array) failed");
    return EXIT_FAILURE;
  }
  std::array<VkPipelineShaderStageCreateInfo, 2> ta_stages{};
  ta_stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  ta_stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
  ta_stages[0].module = tex_array_vert;
  ta_stages[0].pName = "main";
  ta_stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  ta_stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
  ta_stages[1].module = tex_array_frag;
  ta_stages[1].pName = "main";
  VkGraphicsPipelineCreateInfo ta_gpci{};
  ta_gpci.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
  ta_gpci.stageCount = static_cast<std::uint32_t>(ta_stages.size());
  ta_gpci.pStages = ta_stages.data();
  ta_gpci.pVertexInputState = &vi;
  ta_gpci.pInputAssemblyState = &ia;
  ta_gpci.pViewportState = &vp;
  ta_gpci.pRasterizationState = &rs;
  ta_gpci.pMultisampleState = &ms;
  ta_gpci.pColorBlendState = &tex_cb;  // premultiplied alpha, same as textured / needle
  ta_gpci.layout = tex_array_pipeline_layout;
  ta_gpci.renderPass = render_pass;
  ta_gpci.subpass = 1;
  VkPipeline tex_array_pipeline = VK_NULL_HANDLE;
  if (vkCreateGraphicsPipelines(vk_device, VK_NULL_HANDLE, 1, &ta_gpci, nullptr,
                                &tex_array_pipeline) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateGraphicsPipelines (tex_array) failed");
    return EXIT_FAILURE;
  }

  // Pre-computed dst rects for the info readout + warn cells.
  const TexArrayPushConstants info_pc{
      make_quad_pc(info_x, info_y, k_info_w, k_info_h, fb_w, fb_h).dst_x0,
      make_quad_pc(info_x, info_y, k_info_w, k_info_h, fb_w, fb_h).dst_y0,
      make_quad_pc(info_x, info_y, k_info_w, k_info_h, fb_w, fb_h).dst_x1,
      make_quad_pc(info_x, info_y, k_info_w, k_info_h, fb_w, fb_h).dst_y1,
      0.0F,
      0.0F,
      1.0F,
      1.0F,
      0,
      0,
      0,
      0,
  };
  std::array<TexArrayPushConstants, k_warn_count> warn_pcs{};
  for (int cell = 0; cell < k_warn_count; ++cell) {
    const std::int32_t cx0 = warn_x0 + (cell * static_cast<std::int32_t>(k_warn_w));
    const auto q = make_quad_pc(cx0, warn_y, k_warn_w, k_warn_h, fb_w, fb_h);
    // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-constant-array-index)
    warn_pcs[static_cast<std::size_t>(cell)] = TexArrayPushConstants{
        q.dst_x0, q.dst_y0, q.dst_x1, q.dst_y1, 0.0F, 0.0F,
        1.0F,     1.0F,     0,        0,        0,    0,  // layer filled per-frame
    };
  }

  drm::PageFlip page_flip(device);
  bool flip_pending = false;
  page_flip.set_handler([&](std::uint32_t, std::uint64_t, std::uint64_t) { flip_pending = false; });

  // First commit: scene comes up with the (zero-initialized) Vulkan
  // image on PRIMARY. The visible result is plain black for one
  // frame; the first render loop iteration immediately overwrites it.
  if (auto r = scene->commit(DRM_MODE_PAGE_FLIP_EVENT, &page_flip); !r) {
    drm::println(stderr, "first commit: {}", r.error().message());
    return EXIT_FAILURE;
  }
  flip_pending = true;

  using clk = std::chrono::steady_clock;
  const auto t0 = clk::now();
  const auto deadline = t0 + std::chrono::seconds(args.seconds);
  std::uint64_t frames = 0;

  // Optional jitter capture, env-gated to match cluster_sim.
  const bool jitter_enabled = std::getenv("CLUSTER_SIM_FRAME_JITTER") != nullptr;
  // Diagnostic: pin the needle to a fixed position so motion-correlated
  // artifacts can be distinguished from static rendering artifacts.
  const bool freeze_needle = std::getenv("CLUSTER_SIM_VULKAN_FREEZE_NEEDLE") != nullptr;
  // Diagnostic: skip the textured-quad draw so only the bg gradient
  // renders. Helps narrow down where rendering artifacts come from.
  const bool skip_dial = std::getenv("CLUSTER_SIM_VULKAN_SKIP_DIAL") != nullptr;
  auto last_flip = clk::now();
  double max_dt_us = 0.0;
  double sum_dt_us = 0.0;
  std::uint64_t jitter_samples = 0;

  const BgPushConstants bg_pc{static_cast<float>(fb_w), static_cast<float>(fb_h)};
  // Ping-pong index. Render into vk_images[back_index] while KMS scans
  // the other one. Start at 1 so bg[0] (PRIMARY, initial-commit
  // visible) stays untouched on the first iteration.
  int back_index = 1;

  while (clk::now() < deadline && !g_quit.load(std::memory_order_relaxed)) {
    // Wait for previous flip.
    while (flip_pending && !g_quit.load(std::memory_order_relaxed)) {
      (void)page_flip.dispatch(0);
    }
    if (g_quit.load(std::memory_order_relaxed)) {
      break;
    }
    if (jitter_enabled) {
      const auto now = clk::now();
      const double dt = std::chrono::duration<double, std::micro>(now - last_flip).count();
      if (jitter_samples > 0) {
        sum_dt_us += dt;
        max_dt_us = std::max(dt, max_dt_us);
      }
      last_flip = now;
      ++jitter_samples;
    }

    const double t = std::chrono::duration<double>(clk::now() - t0).count();

    vkResetCommandBuffer(cmd, 0);
    VkCommandBufferBeginInfo cbi{};
    cbi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    cbi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(cmd, &cbi);

    VkRenderPassBeginInfo rpbi{};
    rpbi.sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO;
    rpbi.renderPass = render_pass;
    // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-constant-array-index)
    rpbi.framebuffer = framebuffers[back_index];
    rpbi.renderArea.offset = {0, 0};
    rpbi.renderArea.extent = {fb_w, fb_h};
    rpbi.clearValueCount = 0;
    rpbi.pClearValues = nullptr;
    vkCmdBeginRenderPass(cmd, &rpbi, VK_SUBPASS_CONTENTS_INLINE);

    // Subpass 0: bg radial gradient via full-screen triangle.
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline);
    vkCmdPushConstants(cmd, pipeline_layout, VK_SHADER_STAGE_FRAGMENT_BIT, 0, sizeof(bg_pc),
                       &bg_pc);
    vkCmdDraw(cmd, 3, 1, 0, 0);

    // Subpass 1: two textured dial templates side by side, then the
    // matching SDF needles + hubs on top of each.
    vkCmdNextSubpass(cmd, VK_SUBPASS_CONTENTS_INLINE);
    // Sweep values are needed by dial_fx (redline intensity) and the
    // needle pipeline (angle), so compute them up front. The first
    // k_startup_sweep_s seconds both needles do a "self-test" 0→1→0
    // triangle ramp; after that the speedo uses its smooth cosine
    // and the tach uses an engine-rev curve.
    double speedo_norm = NAN;
    double tach_norm = NAN;
    if (freeze_needle) {
      speedo_norm = 0.0;
      tach_norm = 0.0;
    } else if (t < k_startup_sweep_s) {
      const double s = startup_sweep_norm(t);
      speedo_norm = s;
      tach_norm = s;
    } else {
      const double t_anim = t - k_startup_sweep_s;
      speedo_norm = dial_norm_from_phase(t_anim / k_speedo_period_s);
      tach_norm = tach_revs_from_phase(t_anim / k_tach_period_s);
    }
    const auto speedo_angle = static_cast<float>(
        k_dial_start_angle + (std::clamp(speedo_norm, 0.0, 1.0) * k_dial_sweep_angle));
    const auto tach_angle = static_cast<float>(
        k_dial_start_angle + (std::clamp(tach_norm, 0.0, 1.0) * k_dial_sweep_angle));
    // smoothstep(0.80, 1.0, x): 0 below 80% of sweep, ramps to 1 at full.
    auto smoothstep01 = [](double a, double b, double x) {
      double const t01 = std::clamp((x - a) / (b - a), 0.0, 1.0);
      return t01 * t01 * (3.0 - 2.0 * t01);
    };
    const float speedo_redline = 0.0F;  // speedo never goes "redline"
    const auto tach_redline = static_cast<float>(smoothstep01(0.80, 1.0, tach_norm));

    if (!skip_dial) {
      vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, tex_pipeline);
      vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, tex_pipeline_layout, 0, 1,
                              &dset, 0, nullptr);
      vkCmdPushConstants(cmd, tex_pipeline_layout, VK_SHADER_STAGE_VERTEX_BIT, 0, sizeof(speedo_pc),
                         &speedo_pc);
      vkCmdDraw(cmd, 6, 1, 0, 0);
      vkCmdPushConstants(cmd, tex_pipeline_layout, VK_SHADER_STAGE_VERTEX_BIT, 0, sizeof(tach_pc),
                         &tach_pc);
      vkCmdDraw(cmd, 6, 1, 0, 0);

      // Metallic rim highlight + top-half gloss over each dial; the
      // tach also gets a redline tint that ramps up as the needle
      // climbs past 80% of its sweep.
      vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, dial_fx_pipeline);
      const DialFxPushConstants speedo_dfx{
          speedo_pc.dst_x0,
          speedo_pc.dst_y0,
          speedo_pc.dst_x1,
          speedo_pc.dst_y1,
          speedo_pc.uv_x0,
          speedo_pc.uv_y0,
          speedo_pc.uv_x1,
          speedo_pc.uv_y1,
          speedo_redline,
          0.0F,
          0.0F,
          0.0F,
      };
      vkCmdPushConstants(cmd, dial_fx_pipeline_layout,
                         VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT, 0,
                         sizeof(speedo_dfx), &speedo_dfx);
      vkCmdDraw(cmd, 6, 1, 0, 0);
      const DialFxPushConstants tach_dfx{
          tach_pc.dst_x0, tach_pc.dst_y0, tach_pc.dst_x1, tach_pc.dst_y1,
          tach_pc.uv_x0,  tach_pc.uv_y0,  tach_pc.uv_x1,  tach_pc.uv_y1,
          tach_redline,   0.0F,           0.0F,           0.0F,
      };
      vkCmdPushConstants(cmd, dial_fx_pipeline_layout,
                         VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT, 0,
                         sizeof(tach_dfx), &tach_dfx);
      vkCmdDraw(cmd, 6, 1, 0, 0);
    }

    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, needle_pipeline);

    NeedlePushConstants speedo_needle_pc{
        speedo_pc.dst_x0,
        speedo_pc.dst_y0,
        speedo_pc.dst_x1,
        speedo_pc.dst_y1,
        speedo_pc.uv_x0,
        speedo_pc.uv_y0,
        speedo_pc.uv_x1,
        speedo_pc.uv_y1,
        k_speedo_needle_rgba[0],
        k_speedo_needle_rgba[1],
        k_speedo_needle_rgba[2],
        k_speedo_needle_rgba[3],
        speedo_angle,
        k_r_needle_norm,
        k_r_hub_norm,
        k_half_thickness_norm,
        speedo_redline,
    };
    vkCmdPushConstants(cmd, needle_pipeline_layout,
                       VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT, 0,
                       sizeof(speedo_needle_pc), &speedo_needle_pc);
    vkCmdDraw(cmd, 6, 1, 0, 0);

    NeedlePushConstants tach_needle_pc{
        tach_pc.dst_x0,
        tach_pc.dst_y0,
        tach_pc.dst_x1,
        tach_pc.dst_y1,
        tach_pc.uv_x0,
        tach_pc.uv_y0,
        tach_pc.uv_x1,
        tach_pc.uv_y1,
        k_tach_needle_rgba[0],
        k_tach_needle_rgba[1],
        k_tach_needle_rgba[2],
        k_tach_needle_rgba[3],
        tach_angle,
        k_r_needle_norm,
        k_r_hub_norm,
        k_half_thickness_norm,
        tach_redline,
    };
    vkCmdPushConstants(cmd, needle_pipeline_layout,
                       VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT, 0,
                       sizeof(tach_needle_pc), &tach_needle_pc);
    vkCmdDraw(cmd, 6, 1, 0, 0);

    // Info readout: current speed-derived layer index into the
    // 241-layer info texture array, drawn between the dials.
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, tex_array_pipeline);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, tex_array_pipeline_layout, 0, 1,
                            &info_dset, 0, nullptr);
    {
      const auto speed_kmh = static_cast<std::uint32_t>(
          std::lround(std::clamp(speedo_norm * static_cast<double>(k_info_speed_max_kmh), 0.0,
                                 static_cast<double>(k_info_speed_max_kmh))));
      TexArrayPushConstants pc = info_pc;
      pc.layer =
          static_cast<std::int32_t>(std::min<std::uint32_t>(speed_kmh, k_info_layer_count - 1U));
      vkCmdPushConstants(cmd, tex_array_pipeline_layout,
                         VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT, 0, sizeof(pc),
                         &pc);
      vkCmdDraw(cmd, 6, 1, 0, 0);
    }

    // Warn cells: each cell's "lit" state cycles on a 1-Hz schedule
    // offset per-cell so something is always changing — the texture
    // array layer = (cell * 2) for lit, (cell * 2) + 1 for dim.
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, tex_array_pipeline_layout, 0, 1,
                            &warn_dset, 0, nullptr);
    for (int cell = 0; cell < k_warn_count; ++cell) {
      const double phase = t + (cell * 0.37);
      const bool lit = (static_cast<int>(std::floor(phase)) & 1) == 0;
      // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-constant-array-index)
      TexArrayPushConstants pc = warn_pcs[static_cast<std::size_t>(cell)];
      pc.layer = static_cast<std::int32_t>((cell * 2) + (lit ? 0 : 1));
      vkCmdPushConstants(cmd, tex_array_pipeline_layout,
                         VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT, 0, sizeof(pc),
                         &pc);
      vkCmdDraw(cmd, 6, 1, 0, 0);
    }

    vkCmdEndRenderPass(cmd);

    // Release the image to the foreign queue family (the KMS scanout
    // consumer). The subpass dependency above already ordered the
    // color-attachment writes to BOTTOM_OF_PIPE, but on this Tegra
    // driver that's not sufficient to make the writes visible to the
    // display controller through the DMA-BUF view — without this
    // explicit ownership transfer KMS occasionally scans out tiles
    // that still have unflushed cache contents.
    VkImageMemoryBarrier release{};
    release.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
    release.srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
    release.dstAccessMask = 0;
    release.oldLayout = VK_IMAGE_LAYOUT_GENERAL;
    release.newLayout = VK_IMAGE_LAYOUT_GENERAL;
    release.srcQueueFamilyIndex = qf_index;
    release.dstQueueFamilyIndex = VK_QUEUE_FAMILY_FOREIGN_EXT;
    // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-constant-array-index)
    release.image = vk_images[back_index];
    release.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
                         VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT, 0, 0, nullptr, 0, nullptr, 1,
                         &release);

    vkEndCommandBuffer(cmd);

    VkSubmitInfo si{};
    si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    si.commandBufferCount = 1;
    si.pCommandBuffers = &cmd;
    vkQueueSubmit(queue, 1, &si, VK_NULL_HANDLE);
    vkQueueWaitIdle(queue);

    // The next commit's acquire() should return the FB we just
    // rendered into. The plane page-flips between the two FBs.
    swap_source_raw->set_front(back_index);

    if (auto r = scene->commit(DRM_MODE_PAGE_FLIP_EVENT | DRM_MODE_ATOMIC_NONBLOCK, &page_flip);
        !r) {
      drm::println(stderr, "commit: {}", r.error().message());
      break;
    }
    flip_pending = true;
    back_index = 1 - back_index;
    ++frames;
  }
  drm::println(stderr, "cluster_sim_vulkan: {} frames in {}s", frames, args.seconds);
  if (jitter_enabled && jitter_samples > 1) {
    const double mean = sum_dt_us / static_cast<double>(jitter_samples - 1);
    drm::println(stderr, "frame-jitter: frames={} mean={:.1f}us max={:.1f}us", jitter_samples, mean,
                 max_dt_us);
  }

  // Wait for any pending flip before tearing down.
  while (flip_pending) {
    (void)page_flip.dispatch(0);
  }

  scene.reset();
  vkDestroyPipeline(vk_device, dial_fx_pipeline, nullptr);
  vkDestroyPipelineLayout(vk_device, dial_fx_pipeline_layout, nullptr);
  vkDestroyShaderModule(vk_device, dial_fx_frag, nullptr);
  vkDestroyPipeline(vk_device, tex_array_pipeline, nullptr);
  vkDestroyPipelineLayout(vk_device, tex_array_pipeline_layout, nullptr);
  vkDestroyShaderModule(vk_device, tex_array_frag, nullptr);
  vkDestroyShaderModule(vk_device, tex_array_vert, nullptr);
  vkDestroyImageView(vk_device, warn_view, nullptr);
  vkDestroyImageView(vk_device, info_view, nullptr);
  vkFreeMemory(vk_device, warn_mem, nullptr);
  vkDestroyImage(vk_device, warn_image, nullptr);
  vkFreeMemory(vk_device, info_mem, nullptr);
  vkDestroyImage(vk_device, info_image, nullptr);
  vkDestroyPipeline(vk_device, needle_pipeline, nullptr);
  vkDestroyPipelineLayout(vk_device, needle_pipeline_layout, nullptr);
  vkDestroyShaderModule(vk_device, needle_frag, nullptr);
  vkDestroyShaderModule(vk_device, needle_vert, nullptr);
  vkDestroyPipeline(vk_device, tex_pipeline, nullptr);
  vkDestroyPipelineLayout(vk_device, tex_pipeline_layout, nullptr);
  vkDestroyShaderModule(vk_device, tex_frag, nullptr);
  vkDestroyShaderModule(vk_device, tex_vert, nullptr);
  vkDestroyDescriptorPool(vk_device, dpool, nullptr);
  vkDestroyDescriptorSetLayout(vk_device, dsl, nullptr);
  vkDestroySampler(vk_device, dial_sampler, nullptr);
  vkDestroyImageView(vk_device, dial_view, nullptr);
  vkFreeMemory(vk_device, dial_mem, nullptr);
  vkDestroyImage(vk_device, dial_image, nullptr);
  vkDestroyPipeline(vk_device, pipeline, nullptr);
  vkDestroyPipelineLayout(vk_device, pipeline_layout, nullptr);
  vkDestroyShaderModule(vk_device, bg_frag, nullptr);
  vkDestroyShaderModule(vk_device, bg_vert, nullptr);
  for (int i = 0; i < k_swap_count; ++i) {
    // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-constant-array-index)
    vkDestroyFramebuffer(vk_device, framebuffers[i], nullptr);
    // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-constant-array-index)
    vkDestroyImageView(vk_device, image_views[i], nullptr);
  }
  vkDestroyRenderPass(vk_device, render_pass, nullptr);
  vkDestroyCommandPool(vk_device, cmd_pool, nullptr);
  for (int i = 0; i < k_swap_count; ++i) {
    // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-constant-array-index)
    vkFreeMemory(vk_device, vk_mems[i], nullptr);
    // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-constant-array-index)
    vkDestroyImage(vk_device, vk_images[i], nullptr);
  }
  vkDestroyDevice(vk_device, nullptr);
  vkDestroyInstance(instance, nullptr);
  return EXIT_SUCCESS;
}
