// SPDX-FileCopyrightText: (c) 2025 The drm-cxx Contributors
// SPDX-License-Identifier: MIT
//
// cluster_sim_vulkan — instrument-cluster sibling of `cluster_sim`.
// The bg + static dial face are rendered through Vulkan onto one
// DMA-BUF-exported VkImage scanning out on the PRIMARY plane; a thin
// CPU OVERLAY layer carries the moving needle + hub on top. One
// render pass, two Vulkan graphics pipelines:
//
//   1. bg pipeline      — full-screen triangle + bg.vert/bg.frag, paints
//                         cluster_sim's radial gradient (center #101626,
//                         edge #02040A, radius max(w,h)*0.6).
//   2. textured pipeline — UV-mapped quad + textured.vert/textured.frag,
//                         samples a Blend2D-painted dial template (rim
//                         + face + ticks) that's been uploaded once at
//                         startup, alpha-blended over the bg.
//
// Output is DRM_FORMAT_MOD_LINEAR ARGB8888, exported as a DMA-BUF, and
// wrapped in ExternalDmaBufSource like the MVP. The CPU OVERLAY layer
// is a square dial-sized dumb buffer that Blend2D-paints a single red
// needle + dark hub into each frame; rim/face/ticks come from the
// Vulkan textured dial template underneath. The needle moves to a
// follow-up SDF pipeline in a later iteration so the CPU overlay can
// go away entirely.
//
// CLI mirrors `cluster_sim`:
//   cluster_sim_vulkan [--seconds N] [--mode WxH[@Hz]] [/dev/dri/cardN]
//
// Build gate: this TU is built only when `vulkan` is on, Blend2D is
// available, AND glslangValidator is found (it compiles the bg shaders
// at configure-with-build time and writes SPIR-V into headers that
// `#include` below).

#include "../../common/open_output.hpp"

#include <drm-cxx/core/resources.hpp>
#include <drm-cxx/detail/format.hpp>
#include <drm-cxx/detail/span.hpp>
#include <drm-cxx/modeset/mode.hpp>
#include <drm-cxx/modeset/page_flip.hpp>
#include <drm-cxx/scene/buffer_source.hpp>
#include <drm-cxx/scene/dumb_buffer_source.hpp>
#include <drm-cxx/scene/external_dma_buf_source.hpp>
#include <drm-cxx/scene/layer_desc.hpp>
#include <drm-cxx/scene/layer_scene.hpp>

#include <drm_fourcc.h>
#include <vulkan/vulkan_core.h>

// SPIR-V byte arrays generated by glslangValidator at build time.
// Build dir is on the include path via meson.
#include "bg_vert_spv.h"        // k_bg_vert_spv
#include "bg_frag_spv.h"        // k_bg_frag_spv
#include "textured_vert_spv.h"  // k_textured_vert_spv
#include "textured_frag_spv.h"  // k_textured_frag_spv

// Blend2D umbrella: <blend2d/blend2d.h> on most distros, <blend2d.h>
// in older drops; cover both like cluster_sim does.
#if __has_include(<blend2d/blend2d.h>)
#include <blend2d/blend2d.h>  // NOLINT(misc-include-cleaner)
#elif __has_include(<blend2d.h>)
#include <blend2d.h>          // NOLINT(misc-include-cleaner)
#else
#error "Blend2D headers not found; cluster_sim_vulkan needs Blend2D installed"
#endif

#include <algorithm>
#include <array>
#include <atomic>
#include <chrono>
#include <cmath>
#include <csignal>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <optional>
#include <string>
#include <string_view>
#include <sys/stat.h>
#include <sys/sysmacros.h>
#include <unistd.h>
#include <utility>
#include <vector>

namespace {

constexpr int k_default_seconds = 30;
constexpr double k_pi = 3.141592653589793;
// Dial sweep matches cluster_sim's: 3π/4 at the bottom-left, 3π/2 wide.
constexpr double k_dial_start_angle = 3.0 * k_pi / 4.0;
constexpr double k_dial_sweep_angle = 3.0 * k_pi / 2.0;
constexpr double k_speedo_period_s = 6.0;

struct Args {
  int seconds{k_default_seconds};
  std::optional<std::tuple<std::uint32_t, std::uint32_t, std::uint32_t>> mode_override;
};

std::atomic<bool> g_quit{false};
void on_sigint(int /*signo*/) noexcept { g_quit.store(true, std::memory_order_relaxed); }

[[nodiscard]] Args parse_args(int& argc, char**& argv) {
  Args a;
  int write = 1;
  for (int i = 1; i < argc; ++i) {
    const std::string_view arg{argv[i]};
    if (arg == "--seconds" && (i + 1) < argc) {
      a.seconds = std::atoi(argv[++i]);
    } else if (arg == "--mode" && (i + 1) < argc) {
      const std::string spec{argv[++i]};
      std::uint32_t w = 0;
      std::uint32_t h = 0;
      std::uint32_t hz = 0;
      auto* end = spec.data() + spec.size();
      auto* p = spec.data();
      auto consume = [&](std::uint32_t& out) {
        std::uint32_t v = 0;
        bool any = false;
        while (p < end && *p >= '0' && *p <= '9') {
          v = (v * 10U) + static_cast<std::uint32_t>(*p++ - '0');
          any = true;
        }
        if (any) {
          out = v;
        }
        return any;
      };
      if (consume(w) && p < end) {
        ++p;  // 'x'
        if (consume(h)) {
          if (p < end && *p == '@') {
            ++p;
            (void)consume(hz);
          }
          a.mode_override.emplace(w, h, hz);
        }
      }
    } else {
      argv[write++] = argv[i];
    }
  }
  argc = write;
  return a;
}

// Find the VkPhysicalDevice whose DRM major/minor matches the
// rendered-from KMS device. Cross-device dma-buf import works on some
// drivers but is non-portable.
[[nodiscard]] VkPhysicalDevice pick_physical_device(VkInstance instance, int drm_fd) {
  struct stat st{};
  if (fstat(drm_fd, &st) != 0) {
    return VK_NULL_HANDLE;
  }
  const unsigned int want_major = major(st.st_rdev);
  const unsigned int want_minor = minor(st.st_rdev);

  std::uint32_t count = 0;
  vkEnumeratePhysicalDevices(instance, &count, nullptr);
  if (count == 0) {
    return VK_NULL_HANDLE;
  }
  std::vector<VkPhysicalDevice> devices(count);
  vkEnumeratePhysicalDevices(instance, &count, devices.data());

  auto get_drm_props = reinterpret_cast<
      PFN_vkGetPhysicalDeviceProperties2>(  // NOLINT(cppcoreguidelines-pro-type-reinterpret-cast)
      vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceProperties2"));
  if (get_drm_props == nullptr) {
    return devices.front();
  }

  for (auto* pd : devices) {
    VkPhysicalDeviceDrmPropertiesEXT drm_props{};
    drm_props.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DRM_PROPERTIES_EXT;
    VkPhysicalDeviceProperties2 props2{};
    props2.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2;
    props2.pNext = &drm_props;
    get_drm_props(pd, &props2);
    if ((drm_props.hasPrimary != VK_FALSE && drm_props.primaryMajor == want_major &&
         drm_props.primaryMinor == want_minor) ||
        (drm_props.hasRender != VK_FALSE && drm_props.renderMajor == want_major &&
         drm_props.renderMinor == want_minor)) {
      return pd;
    }
  }
  return devices.front();
}

[[nodiscard]] std::uint32_t find_memory_type(VkPhysicalDevice pd, std::uint32_t type_bits,
                                             VkMemoryPropertyFlags flags) {
  VkPhysicalDeviceMemoryProperties mp{};
  vkGetPhysicalDeviceMemoryProperties(pd, &mp);
  const drm::span<const VkMemoryType> types{mp.memoryTypes, mp.memoryTypeCount};
  for (std::uint32_t i = 0; i < types.size(); ++i) {
    if (((type_bits >> i) & 1U) == 0U) {
      continue;
    }
    if ((types[i].propertyFlags & flags) == flags) {
      return i;
    }
  }
  return 0xFFFFFFFFU;
}

[[nodiscard]] double dial_norm_from_phase(double phase01) noexcept {
  return 0.5 * (1.0 - std::cos(2.0 * k_pi * phase01));
}

// Paint the static parts of a dial — rim + face + ticks — into a
// dial_size × dial_size buffer. Pixel format is PRGB32 (premultiplied
// BGRA bytes), which lines up with VK_FORMAT_B8G8R8A8_UNORM when the
// buffer is the source of a buffer-to-image copy. Geometry proportions
// mirror cluster_sim's paint_dial_template so the two examples agree.
// Caller hands in a tightly packed buffer (stride = dial_size * 4).
void paint_dial_template(std::uint8_t* pixels, std::uint32_t dial_size) noexcept {
  if (pixels == nullptr || dial_size == 0U) {
    return;
  }
  const auto stride_bytes = static_cast<intptr_t>(dial_size) * 4;
  BLImage canvas;
  if (canvas.create_from_data(static_cast<int>(dial_size), static_cast<int>(dial_size),
                              BL_FORMAT_PRGB32, pixels, stride_bytes, BL_DATA_ACCESS_RW,
                              nullptr, nullptr) != BL_SUCCESS) {
    return;
  }
  BLContext ctx(canvas);
  // alpha=0 background — the textured-quad pipeline alpha-blends, so
  // the bg gradient shows through the dial's four corners.
  ctx.set_comp_op(BL_COMP_OP_SRC_COPY);
  ctx.fill_all(BLRgba32(0x00000000U));
  ctx.set_comp_op(BL_COMP_OP_SRC_OVER);

  const double size = static_cast<double>(dial_size);
  const double cx = size / 2.0;
  const double cy = size / 2.0;
  const double r_outer = size * 0.48;
  const double r_inner = size * 0.42;
  const double r_tick_outer = size * 0.46;
  const double r_tick_inner = size * 0.38;
  constexpr int k_major_ticks = 12;

  ctx.fill_circle(BLCircle(cx, cy, r_outer), BLRgba32(0xFF606870U));   // rim
  ctx.fill_circle(BLCircle(cx, cy, r_inner), BLRgba32(0xFF080C18U));   // face

  ctx.set_stroke_width(std::max(2.0, size * 0.004));
  ctx.set_stroke_caps(BL_STROKE_CAP_ROUND);
  for (int i = 0; i <= k_major_ticks; ++i) {
    const double t = static_cast<double>(i) / static_cast<double>(k_major_ticks);
    const double a = k_dial_start_angle + (t * k_dial_sweep_angle);
    const double x1 = cx + (r_tick_inner * std::cos(a));
    const double y1 = cy + (r_tick_inner * std::sin(a));
    const double x2 = cx + (r_tick_outer * std::cos(a));
    const double y2 = cy + (r_tick_outer * std::sin(a));
    ctx.stroke_line(BLPoint(x1, y1), BLPoint(x2, y2), BLRgba32(0xFFC0C8D0U));
  }
  ctx.end();
}

// Per-frame CPU overlay: paint only the needle + hub on a fully
// transparent buffer. The Vulkan-side textured dial template provides
// the rim + face + ticks underneath; the OVERLAY plane lands the
// moving parts on top.
void paint_needle_only(drm::BufferMapping& mapping, std::uint32_t width, std::uint32_t height,
                       double norm) noexcept {
  if (width == 0U || height == 0U) {
    return;
  }
  drm::span<std::uint8_t> const pixels = mapping.pixels();
  std::uint32_t const stride = mapping.stride();
  if (pixels.size() < static_cast<std::size_t>(height) * stride) {
    return;
  }
  BLImage canvas;
  if (canvas.create_from_data(static_cast<int>(width), static_cast<int>(height), BL_FORMAT_PRGB32,
                              pixels.data(), static_cast<intptr_t>(stride), BL_DATA_ACCESS_RW,
                              nullptr, nullptr) != BL_SUCCESS) {
    return;
  }
  BLContext ctx(canvas);
  ctx.set_comp_op(BL_COMP_OP_SRC_COPY);
  ctx.fill_all(BLRgba32(0x00000000U));
  ctx.set_comp_op(BL_COMP_OP_SRC_OVER);

  const double size = static_cast<double>(std::min(width, height));
  const double cx = size / 2.0;
  const double cy = size / 2.0;
  const double r_needle = size * 0.40;
  const double r_hub = size * 0.06;
  const double a = k_dial_start_angle + (std::clamp(norm, 0.0, 1.0) * k_dial_sweep_angle);
  const double nx = cx + (r_needle * std::cos(a));
  const double ny = cy + (r_needle * std::sin(a));
  ctx.set_stroke_width(std::max(3.0, size * 0.008));
  ctx.set_stroke_caps(BL_STROKE_CAP_ROUND);
  ctx.stroke_line(BLPoint(cx, cy), BLPoint(nx, ny), BLRgba32(0xFFFF3B30U));
  ctx.fill_circle(BLCircle(cx, cy, r_hub), BLRgba32(0xFF1A1F2CU));
  ctx.end();
}

[[nodiscard]] VkShaderModule make_shader_module(VkDevice dev, const std::uint32_t* code,
                                                std::size_t code_bytes) {
  VkShaderModuleCreateInfo info{};
  info.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
  info.codeSize = code_bytes;
  info.pCode = code;
  VkShaderModule mod = VK_NULL_HANDLE;
  if (vkCreateShaderModule(dev, &info, nullptr, &mod) != VK_SUCCESS) {
    return VK_NULL_HANDLE;
  }
  return mod;
}

// Push-constant block for the bg fragment shader.
struct BgPushConstants {
  float extent_x;
  float extent_y;
};

// Push-constant block for the textured-quad vertex shader. dst is in
// NDC (x0, y0, x1, y1); uv is in [0, 1]. 32 bytes total — comfortably
// under the 128-byte minimum guaranteed by Vulkan.
struct TexturedPushConstants {
  float dst_x0;
  float dst_y0;
  float dst_x1;
  float dst_y1;
  float uv_x0;
  float uv_y0;
  float uv_x1;
  float uv_y1;
};

// Pixel rectangle → NDC. Vulkan NDC y is +1 at the bottom and -1 at
// the top by default (matches gl_Position with no flip), so a pixel
// y of 0 (top of the framebuffer) maps to -1.
[[nodiscard]] TexturedPushConstants make_quad_pc(std::int32_t px, std::int32_t py,
                                                 std::uint32_t pw, std::uint32_t ph,
                                                 std::uint32_t fb_w, std::uint32_t fb_h) noexcept {
  const auto fw = static_cast<float>(fb_w);
  const auto fh = static_cast<float>(fb_h);
  const float x0 = (static_cast<float>(px) / fw) * 2.0F - 1.0F;
  const float y0 = (static_cast<float>(py) / fh) * 2.0F - 1.0F;
  const float x1 = (static_cast<float>(px + static_cast<std::int32_t>(pw)) / fw) * 2.0F - 1.0F;
  const float y1 = (static_cast<float>(py + static_cast<std::int32_t>(ph)) / fh) * 2.0F - 1.0F;
  return TexturedPushConstants{x0, y0, x1, y1, 0.0F, 0.0F, 1.0F, 1.0F};
}

}  // namespace

int main(int argc, char* argv[]) {
  std::signal(SIGINT, on_sigint);
  std::signal(SIGTERM, on_sigint);

  Args args = parse_args(argc, argv);

  auto out = drm::examples::open_and_pick_output(argc, argv);
  if (!out) {
    return EXIT_FAILURE;
  }
  auto& device = out->device;

  if (args.mode_override.has_value()) {
    const auto [tw, th, thz] = *args.mode_override;
    auto conn = drm::get_connector(device.fd(), out->connector_id);
    if (conn) {
      auto picked = drm::select_mode(
          drm::span<const drmModeModeInfo>(conn->modes, conn->count_modes), tw, th, thz);
      if (picked) {
        const auto& m = picked->drm_mode;
        if (m.hdisplay == tw && m.vdisplay == th && (thz == 0 || m.vrefresh == thz)) {
          out->mode = m;
        }
      }
    }
  }

  const std::uint32_t fb_w = out->mode.hdisplay;
  const std::uint32_t fb_h = out->mode.vdisplay;
  drm::println(stderr, "cluster_sim_vulkan: mode = {}x{}@{}Hz crtc={} connector={}", fb_w, fb_h,
               out->mode.vrefresh, out->crtc_id, out->connector_id);

  drm::scene::LayerScene::Config scene_cfg;
  scene_cfg.crtc_id = out->crtc_id;
  scene_cfg.connector_id = out->connector_id;
  scene_cfg.mode = out->mode;
  auto scene_r = drm::scene::LayerScene::create(device, scene_cfg);
  if (!scene_r) {
    drm::println(stderr, "LayerScene::create: {}", scene_r.error().message());
    return EXIT_FAILURE;
  }
  auto& scene = *scene_r;

  // Vulkan instance.
  const std::array<const char*, 2> inst_exts{
      "VK_KHR_get_physical_device_properties2",
      "VK_KHR_external_memory_capabilities",
  };
  VkApplicationInfo app{};
  app.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
  app.apiVersion = VK_API_VERSION_1_1;
  VkInstanceCreateInfo ici{};
  ici.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
  ici.pApplicationInfo = &app;
  ici.enabledExtensionCount = static_cast<std::uint32_t>(inst_exts.size());
  ici.ppEnabledExtensionNames = inst_exts.data();
  VkInstance instance = VK_NULL_HANDLE;
  if (vkCreateInstance(&ici, nullptr, &instance) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateInstance failed");
    return EXIT_FAILURE;
  }

  VkPhysicalDevice pd = pick_physical_device(instance, device.fd());
  if (pd == VK_NULL_HANDLE) {
    drm::println(stderr, "no VkPhysicalDevice matched the DRM fd");
    vkDestroyInstance(instance, nullptr);
    return EXIT_FAILURE;
  }

  std::uint32_t qf_count = 0;
  vkGetPhysicalDeviceQueueFamilyProperties(pd, &qf_count, nullptr);
  std::vector<VkQueueFamilyProperties> qfs(qf_count);
  vkGetPhysicalDeviceQueueFamilyProperties(pd, &qf_count, qfs.data());
  std::uint32_t qf_index = 0xFFFFFFFFU;
  for (std::uint32_t i = 0; i < qf_count; ++i) {
    if ((qfs[i].queueFlags & VK_QUEUE_GRAPHICS_BIT) != 0U) {
      qf_index = i;
      break;
    }
  }
  if (qf_index == 0xFFFFFFFFU) {
    drm::println(stderr, "no graphics queue");
    vkDestroyInstance(instance, nullptr);
    return EXIT_FAILURE;
  }

  const float qp = 1.0F;
  VkDeviceQueueCreateInfo qci{};
  qci.sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
  qci.queueFamilyIndex = qf_index;
  qci.queueCount = 1;
  qci.pQueuePriorities = &qp;
  const std::array<const char*, 4> dev_exts{
      "VK_KHR_external_memory",
      "VK_KHR_external_memory_fd",
      "VK_EXT_external_memory_dma_buf",
      "VK_EXT_image_drm_format_modifier",
  };
  VkDeviceCreateInfo dci{};
  dci.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
  dci.queueCreateInfoCount = 1;
  dci.pQueueCreateInfos = &qci;
  dci.enabledExtensionCount = static_cast<std::uint32_t>(dev_exts.size());
  dci.ppEnabledExtensionNames = dev_exts.data();
  VkDevice vk_device = VK_NULL_HANDLE;
  if (vkCreateDevice(pd, &dci, nullptr, &vk_device) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateDevice failed");
    vkDestroyInstance(instance, nullptr);
    return EXIT_FAILURE;
  }
  VkQueue queue = VK_NULL_HANDLE;
  vkGetDeviceQueue(vk_device, qf_index, 0, &queue);

  // Vulkan-allocated DRM-modifier-LINEAR ARGB8888 image for the bg.
  // Render pass needs COLOR_ATTACHMENT_BIT; TRANSFER_DST_BIT stays in
  // the usage list as a guard (some drivers fold both in image-format
  // queries on the DRM-modifier path).
  const std::uint64_t modifier = DRM_FORMAT_MOD_LINEAR;
  std::array<std::uint64_t, 1> modifiers{modifier};
  VkImageDrmFormatModifierListCreateInfoEXT drm_list{};
  drm_list.sType = VK_STRUCTURE_TYPE_IMAGE_DRM_FORMAT_MODIFIER_LIST_CREATE_INFO_EXT;
  drm_list.drmFormatModifierCount = 1;
  drm_list.pDrmFormatModifiers = modifiers.data();
  VkExternalMemoryImageCreateInfo ext_img{};
  ext_img.sType = VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO;
  ext_img.handleTypes = VK_EXTERNAL_MEMORY_HANDLE_TYPE_DMA_BUF_BIT_EXT;
  ext_img.pNext = &drm_list;
  VkImageCreateInfo iic{};
  iic.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
  iic.pNext = &ext_img;
  iic.imageType = VK_IMAGE_TYPE_2D;
  iic.format = VK_FORMAT_B8G8R8A8_UNORM;  // matches DRM_FORMAT_ARGB8888 byte order
  iic.extent = {fb_w, fb_h, 1};
  iic.mipLevels = 1;
  iic.arrayLayers = 1;
  iic.samples = VK_SAMPLE_COUNT_1_BIT;
  iic.tiling = VK_IMAGE_TILING_DRM_FORMAT_MODIFIER_EXT;
  iic.usage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT;
  iic.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
  iic.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
  VkImage vk_image = VK_NULL_HANDLE;
  if (vkCreateImage(vk_device, &iic, nullptr, &vk_image) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateImage failed");
    vkDestroyDevice(vk_device, nullptr);
    vkDestroyInstance(instance, nullptr);
    return EXIT_FAILURE;
  }
  VkMemoryRequirements mr{};
  vkGetImageMemoryRequirements(vk_device, vk_image, &mr);
  VkExportMemoryAllocateInfo emai{};
  emai.sType = VK_STRUCTURE_TYPE_EXPORT_MEMORY_ALLOCATE_INFO;
  emai.handleTypes = VK_EXTERNAL_MEMORY_HANDLE_TYPE_DMA_BUF_BIT_EXT;
  VkMemoryAllocateInfo mai{};
  mai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
  mai.pNext = &emai;
  mai.allocationSize = mr.size;
  mai.memoryTypeIndex = find_memory_type(pd, mr.memoryTypeBits, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
  if (mai.memoryTypeIndex == 0xFFFFFFFFU) {
    drm::println(stderr, "no DEVICE_LOCAL memory type");
    vkDestroyImage(vk_device, vk_image, nullptr);
    vkDestroyDevice(vk_device, nullptr);
    vkDestroyInstance(instance, nullptr);
    return EXIT_FAILURE;
  }
  VkDeviceMemory vk_mem = VK_NULL_HANDLE;
  if (vkAllocateMemory(vk_device, &mai, nullptr, &vk_mem) != VK_SUCCESS) {
    drm::println(stderr, "vkAllocateMemory failed");
    vkDestroyImage(vk_device, vk_image, nullptr);
    vkDestroyDevice(vk_device, nullptr);
    vkDestroyInstance(instance, nullptr);
    return EXIT_FAILURE;
  }
  vkBindImageMemory(vk_device, vk_image, vk_mem, 0);

  auto get_memory_fd = reinterpret_cast<
      PFN_vkGetMemoryFdKHR>(  // NOLINT(cppcoreguidelines-pro-type-reinterpret-cast)
      vkGetDeviceProcAddr(vk_device, "vkGetMemoryFdKHR"));
  if (get_memory_fd == nullptr) {
    drm::println(stderr, "vkGetMemoryFdKHR missing");
    return EXIT_FAILURE;
  }
  VkMemoryGetFdInfoKHR mgfi{};
  mgfi.sType = VK_STRUCTURE_TYPE_MEMORY_GET_FD_INFO_KHR;
  mgfi.memory = vk_mem;
  mgfi.handleType = VK_EXTERNAL_MEMORY_HANDLE_TYPE_DMA_BUF_BIT_EXT;
  int dmabuf_fd = -1;
  if (get_memory_fd(vk_device, &mgfi, &dmabuf_fd) != VK_SUCCESS || dmabuf_fd < 0) {
    drm::println(stderr, "vkGetMemoryFdKHR failed");
    return EXIT_FAILURE;
  }
  VkImageSubresource sub{};
  sub.aspectMask = VK_IMAGE_ASPECT_MEMORY_PLANE_0_BIT_EXT;
  VkSubresourceLayout layout{};
  vkGetImageSubresourceLayout(vk_device, vk_image, &sub, &layout);
  drm::scene::ExternalPlaneInfo plane_info{};
  plane_info.fd = dmabuf_fd;
  plane_info.pitch = static_cast<std::uint32_t>(layout.rowPitch);
  plane_info.offset = static_cast<std::uint32_t>(layout.offset);
  std::array<drm::scene::ExternalPlaneInfo, 1> planes{plane_info};
  auto bg_source =
      drm::scene::ExternalDmaBufSource::create(device, fb_w, fb_h, DRM_FORMAT_ARGB8888, modifier,
                                                planes);
  ::close(dmabuf_fd);
  if (!bg_source) {
    drm::println(stderr, "ExternalDmaBufSource::create: {}", bg_source.error().message());
    return EXIT_FAILURE;
  }
  drm::scene::LayerDesc bg_desc;
  bg_desc.source = std::move(*bg_source);
  bg_desc.display.src_rect = drm::scene::Rect{0, 0, fb_w, fb_h};
  bg_desc.display.dst_rect = drm::scene::Rect{0, 0, fb_w, fb_h};
  bg_desc.display.zpos = 0;  // Tegra-style affinity: 0 → PRIMARY
  if (auto r = scene->add_layer(std::move(bg_desc)); !r) {
    drm::println(stderr, "add_layer (Vulkan bg): {}", r.error().message());
    return EXIT_FAILURE;
  }

  // Square dial buffer covering the smaller framebuffer dimension —
  // both the Vulkan dial-template texture and the CPU needle overlay
  // use this size, and the centered dst rect lines them up exactly.
  const std::uint32_t dial_size = std::min(fb_w, fb_h);
  const std::int32_t dial_x = static_cast<std::int32_t>((fb_w - dial_size) / 2U);
  const std::int32_t dial_y = static_cast<std::int32_t>((fb_h - dial_size) / 2U);

  // Instruments layer — CPU-painted ARGB on a dumb buffer. Iteration 2
  // has it carrying only the needle + hub; the rim/face/ticks are
  // drawn from the Vulkan textured dial template below.
  auto inst_source =
      drm::scene::DumbBufferSource::create(device, dial_size, dial_size, DRM_FORMAT_ARGB8888);
  if (!inst_source) {
    drm::println(stderr, "DumbBufferSource::create (instruments): {}",
                 inst_source.error().message());
    return EXIT_FAILURE;
  }
  auto inst_src = std::move(*inst_source);
  auto* inst_src_raw = inst_src.get();
  // Initial transparent fill.
  if (auto m = inst_src->map(drm::MapAccess::Write); m) {
    std::memset(m->pixels().data(), 0, m->pixels().size_bytes());
  }
  drm::scene::LayerDesc inst_desc;
  inst_desc.source = std::move(inst_src);
  inst_desc.display.src_rect = drm::scene::Rect{0, 0, dial_size, dial_size};
  inst_desc.display.dst_rect = drm::scene::Rect{dial_x, dial_y, dial_size, dial_size};
  inst_desc.display.zpos = 4;  // Tegra-style affinity: > 0 → OVERLAY
  if (auto r = scene->add_layer(std::move(inst_desc)); !r) {
    drm::println(stderr, "add_layer (instruments): {}", r.error().message());
    return EXIT_FAILURE;
  }

  // -------- Vulkan render-pass plumbing (bg pipeline) -----------------
  // Single color attachment, format matches the image (B8G8R8A8_UNORM).
  // loadOp=DONT_CARE because the shader writes every pixel each frame.
  // finalLayout=GENERAL so KMS reads the post-render image without an
  // extra explicit barrier.
  VkAttachmentDescription attach{};
  attach.format = VK_FORMAT_B8G8R8A8_UNORM;
  attach.samples = VK_SAMPLE_COUNT_1_BIT;
  attach.loadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
  attach.storeOp = VK_ATTACHMENT_STORE_OP_STORE;
  attach.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
  attach.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
  attach.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
  attach.finalLayout = VK_IMAGE_LAYOUT_GENERAL;
  VkAttachmentReference color_ref{};
  color_ref.attachment = 0;
  color_ref.layout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
  VkSubpassDescription subpass{};
  subpass.pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS;
  subpass.colorAttachmentCount = 1;
  subpass.pColorAttachments = &color_ref;
  // External dependency: defer writes until the previous frame's
  // scanout reader has finished — important because the image is
  // single-buffered and the DMA-BUF consumer (KMS) may still be reading
  // when we record the next render.
  std::array<VkSubpassDependency, 2> deps{};
  deps[0].srcSubpass = VK_SUBPASS_EXTERNAL;
  deps[0].dstSubpass = 0;
  deps[0].srcStageMask = VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT;
  deps[0].dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
  deps[0].srcAccessMask = 0;
  deps[0].dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
  deps[0].dependencyFlags = 0;
  deps[1].srcSubpass = 0;
  deps[1].dstSubpass = VK_SUBPASS_EXTERNAL;
  deps[1].srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
  deps[1].dstStageMask = VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT;
  deps[1].srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
  deps[1].dstAccessMask = 0;
  deps[1].dependencyFlags = 0;
  VkRenderPassCreateInfo rpci{};
  rpci.sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
  rpci.attachmentCount = 1;
  rpci.pAttachments = &attach;
  rpci.subpassCount = 1;
  rpci.pSubpasses = &subpass;
  rpci.dependencyCount = static_cast<std::uint32_t>(deps.size());
  rpci.pDependencies = deps.data();
  VkRenderPass render_pass = VK_NULL_HANDLE;
  if (vkCreateRenderPass(vk_device, &rpci, nullptr, &render_pass) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateRenderPass failed");
    return EXIT_FAILURE;
  }

  VkImageViewCreateInfo ivci{};
  ivci.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
  ivci.image = vk_image;
  ivci.viewType = VK_IMAGE_VIEW_TYPE_2D;
  ivci.format = VK_FORMAT_B8G8R8A8_UNORM;
  ivci.components = {VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY,
                     VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY};
  ivci.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
  VkImageView image_view = VK_NULL_HANDLE;
  if (vkCreateImageView(vk_device, &ivci, nullptr, &image_view) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateImageView failed");
    return EXIT_FAILURE;
  }

  VkFramebufferCreateInfo fbci{};
  fbci.sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO;
  fbci.renderPass = render_pass;
  fbci.attachmentCount = 1;
  fbci.pAttachments = &image_view;
  fbci.width = fb_w;
  fbci.height = fb_h;
  fbci.layers = 1;
  VkFramebuffer framebuffer = VK_NULL_HANDLE;
  if (vkCreateFramebuffer(vk_device, &fbci, nullptr, &framebuffer) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateFramebuffer failed");
    return EXIT_FAILURE;
  }

  // Shader modules.
  VkShaderModule bg_vert = make_shader_module(vk_device, k_bg_vert_spv, sizeof(k_bg_vert_spv));
  VkShaderModule bg_frag = make_shader_module(vk_device, k_bg_frag_spv, sizeof(k_bg_frag_spv));
  if (bg_vert == VK_NULL_HANDLE || bg_frag == VK_NULL_HANDLE) {
    drm::println(stderr, "vkCreateShaderModule failed");
    return EXIT_FAILURE;
  }

  // Pipeline layout: a single fragment-stage push constant (extent).
  VkPushConstantRange pcr{};
  pcr.stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;
  pcr.offset = 0;
  pcr.size = sizeof(BgPushConstants);
  VkPipelineLayoutCreateInfo plci{};
  plci.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
  plci.pushConstantRangeCount = 1;
  plci.pPushConstantRanges = &pcr;
  VkPipelineLayout pipeline_layout = VK_NULL_HANDLE;
  if (vkCreatePipelineLayout(vk_device, &plci, nullptr, &pipeline_layout) != VK_SUCCESS) {
    drm::println(stderr, "vkCreatePipelineLayout failed");
    return EXIT_FAILURE;
  }

  std::array<VkPipelineShaderStageCreateInfo, 2> stages{};
  stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
  stages[0].module = bg_vert;
  stages[0].pName = "main";
  stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
  stages[1].module = bg_frag;
  stages[1].pName = "main";

  VkPipelineVertexInputStateCreateInfo vi{};
  vi.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;

  VkPipelineInputAssemblyStateCreateInfo ia{};
  ia.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
  ia.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;

  VkViewport viewport{};
  viewport.x = 0.0F;
  viewport.y = 0.0F;
  viewport.width = static_cast<float>(fb_w);
  viewport.height = static_cast<float>(fb_h);
  viewport.minDepth = 0.0F;
  viewport.maxDepth = 1.0F;
  VkRect2D scissor{};
  scissor.offset = {0, 0};
  scissor.extent = {fb_w, fb_h};
  VkPipelineViewportStateCreateInfo vp{};
  vp.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
  vp.viewportCount = 1;
  vp.pViewports = &viewport;
  vp.scissorCount = 1;
  vp.pScissors = &scissor;

  VkPipelineRasterizationStateCreateInfo rs{};
  rs.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
  rs.polygonMode = VK_POLYGON_MODE_FILL;
  rs.cullMode = VK_CULL_MODE_NONE;
  rs.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE;
  rs.lineWidth = 1.0F;

  VkPipelineMultisampleStateCreateInfo ms{};
  ms.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
  ms.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

  VkPipelineColorBlendAttachmentState cba{};
  cba.blendEnable = VK_FALSE;
  cba.colorWriteMask =
      VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
      VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
  VkPipelineColorBlendStateCreateInfo cb{};
  cb.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
  cb.attachmentCount = 1;
  cb.pAttachments = &cba;

  VkGraphicsPipelineCreateInfo gpci{};
  gpci.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
  gpci.stageCount = static_cast<std::uint32_t>(stages.size());
  gpci.pStages = stages.data();
  gpci.pVertexInputState = &vi;
  gpci.pInputAssemblyState = &ia;
  gpci.pViewportState = &vp;
  gpci.pRasterizationState = &rs;
  gpci.pMultisampleState = &ms;
  gpci.pColorBlendState = &cb;
  gpci.layout = pipeline_layout;
  gpci.renderPass = render_pass;
  gpci.subpass = 0;
  VkPipeline pipeline = VK_NULL_HANDLE;
  if (vkCreateGraphicsPipelines(vk_device, VK_NULL_HANDLE, 1, &gpci, nullptr, &pipeline) !=
      VK_SUCCESS) {
    drm::println(stderr, "vkCreateGraphicsPipelines failed");
    return EXIT_FAILURE;
  }

  // Vulkan command pool + one re-recordable command buffer.
  VkCommandPoolCreateInfo pci{};
  pci.sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
  pci.queueFamilyIndex = qf_index;
  pci.flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
  VkCommandPool cmd_pool = VK_NULL_HANDLE;
  vkCreateCommandPool(vk_device, &pci, nullptr, &cmd_pool);
  VkCommandBufferAllocateInfo cbai{};
  cbai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
  cbai.commandPool = cmd_pool;
  cbai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
  cbai.commandBufferCount = 1;
  VkCommandBuffer cmd = VK_NULL_HANDLE;
  vkAllocateCommandBuffers(vk_device, &cbai, &cmd);

  // -------- Dial template texture + textured-quad pipeline ------------
  // One sampled image holds the static dial face (rim + face + ticks)
  // that Blend2D paints into a host-visible staging buffer at startup.
  // The textured-quad pipeline binds it as a combined image sampler and
  // alpha-blends over the bg gradient inside the same render pass.

  VkImageCreateInfo dial_ici{};
  dial_ici.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
  dial_ici.imageType = VK_IMAGE_TYPE_2D;
  dial_ici.format = VK_FORMAT_B8G8R8A8_UNORM;
  dial_ici.extent = {dial_size, dial_size, 1};
  dial_ici.mipLevels = 1;
  dial_ici.arrayLayers = 1;
  dial_ici.samples = VK_SAMPLE_COUNT_1_BIT;
  dial_ici.tiling = VK_IMAGE_TILING_OPTIMAL;
  dial_ici.usage = VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT;
  dial_ici.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
  dial_ici.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
  VkImage dial_image = VK_NULL_HANDLE;
  if (vkCreateImage(vk_device, &dial_ici, nullptr, &dial_image) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateImage (dial) failed");
    return EXIT_FAILURE;
  }
  VkMemoryRequirements dial_mr{};
  vkGetImageMemoryRequirements(vk_device, dial_image, &dial_mr);
  VkMemoryAllocateInfo dial_mai{};
  dial_mai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
  dial_mai.allocationSize = dial_mr.size;
  dial_mai.memoryTypeIndex = find_memory_type(pd, dial_mr.memoryTypeBits,
                                              VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
  VkDeviceMemory dial_mem = VK_NULL_HANDLE;
  if (vkAllocateMemory(vk_device, &dial_mai, nullptr, &dial_mem) != VK_SUCCESS) {
    drm::println(stderr, "vkAllocateMemory (dial) failed");
    return EXIT_FAILURE;
  }
  vkBindImageMemory(vk_device, dial_image, dial_mem, 0);

  // Staging buffer — host-visible coherent, sized for tightly packed
  // BGRA pixels. Blend2D paints into the mapped pointer.
  const VkDeviceSize dial_bytes =
      static_cast<VkDeviceSize>(dial_size) * dial_size * 4U;
  VkBufferCreateInfo dial_bci{};
  dial_bci.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
  dial_bci.size = dial_bytes;
  dial_bci.usage = VK_BUFFER_USAGE_TRANSFER_SRC_BIT;
  dial_bci.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
  VkBuffer staging_buf = VK_NULL_HANDLE;
  if (vkCreateBuffer(vk_device, &dial_bci, nullptr, &staging_buf) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateBuffer (staging) failed");
    return EXIT_FAILURE;
  }
  VkMemoryRequirements stg_mr{};
  vkGetBufferMemoryRequirements(vk_device, staging_buf, &stg_mr);
  VkMemoryAllocateInfo stg_mai{};
  stg_mai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
  stg_mai.allocationSize = stg_mr.size;
  stg_mai.memoryTypeIndex = find_memory_type(
      pd, stg_mr.memoryTypeBits,
      VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
  VkDeviceMemory staging_mem = VK_NULL_HANDLE;
  if (vkAllocateMemory(vk_device, &stg_mai, nullptr, &staging_mem) != VK_SUCCESS) {
    drm::println(stderr, "vkAllocateMemory (staging) failed");
    return EXIT_FAILURE;
  }
  vkBindBufferMemory(vk_device, staging_buf, staging_mem, 0);

  void* stg_ptr = nullptr;
  vkMapMemory(vk_device, staging_mem, 0, dial_bytes, 0, &stg_ptr);
  // Defensive: vkAllocateMemory doesn't promise zero-init, and
  // Blend2D's fill_all + SRC_OVER drawing only writes pixels the
  // shapes touch — leaving anywhere outside the rim at whatever
  // residual values the allocator returned. Zero first.
  std::memset(stg_ptr, 0, static_cast<std::size_t>(dial_bytes));
  paint_dial_template(static_cast<std::uint8_t*>(stg_ptr), dial_size);
  vkUnmapMemory(vk_device, staging_mem);

  // One-shot upload command buffer: barrier UNDEFINED → TRANSFER_DST,
  // vkCmdCopyBufferToImage, barrier → SHADER_READ_ONLY_OPTIMAL.
  {
    VkCommandBufferBeginInfo upload_cbi{};
    upload_cbi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    upload_cbi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(cmd, &upload_cbi);

    VkImageMemoryBarrier to_dst{};
    to_dst.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
    to_dst.oldLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    to_dst.newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
    to_dst.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    to_dst.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    to_dst.image = dial_image;
    to_dst.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
    to_dst.srcAccessMask = 0;
    to_dst.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
                         VK_PIPELINE_STAGE_TRANSFER_BIT, 0, 0, nullptr, 0, nullptr, 1, &to_dst);

    VkBufferImageCopy region{};
    region.bufferOffset = 0;
    region.bufferRowLength = 0;  // tightly packed
    region.bufferImageHeight = 0;
    region.imageSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
    region.imageOffset = {0, 0, 0};
    region.imageExtent = {dial_size, dial_size, 1};
    vkCmdCopyBufferToImage(cmd, staging_buf, dial_image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1,
                           &region);

    VkImageMemoryBarrier to_shader{};
    to_shader.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
    to_shader.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
    to_shader.newLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
    to_shader.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    to_shader.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    to_shader.image = dial_image;
    to_shader.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
    to_shader.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
    to_shader.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT,
                         VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT, 0, 0, nullptr, 0, nullptr, 1,
                         &to_shader);

    vkEndCommandBuffer(cmd);

    VkSubmitInfo upload_si{};
    upload_si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    upload_si.commandBufferCount = 1;
    upload_si.pCommandBuffers = &cmd;
    vkQueueSubmit(queue, 1, &upload_si, VK_NULL_HANDLE);
    vkQueueWaitIdle(queue);
  }

  // Staging is done with — release it; the dial image owns its
  // contents on the device side now.
  vkDestroyBuffer(vk_device, staging_buf, nullptr);
  vkFreeMemory(vk_device, staging_mem, nullptr);

  VkImageViewCreateInfo dial_ivci{};
  dial_ivci.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
  dial_ivci.image = dial_image;
  dial_ivci.viewType = VK_IMAGE_VIEW_TYPE_2D;
  dial_ivci.format = VK_FORMAT_B8G8R8A8_UNORM;
  dial_ivci.components = {VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY,
                          VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY};
  dial_ivci.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
  VkImageView dial_view = VK_NULL_HANDLE;
  if (vkCreateImageView(vk_device, &dial_ivci, nullptr, &dial_view) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateImageView (dial) failed");
    return EXIT_FAILURE;
  }

  VkSamplerCreateInfo sci{};
  sci.sType = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO;
  sci.magFilter = VK_FILTER_LINEAR;
  sci.minFilter = VK_FILTER_LINEAR;
  sci.mipmapMode = VK_SAMPLER_MIPMAP_MODE_NEAREST;
  sci.addressModeU = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
  sci.addressModeV = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
  sci.addressModeW = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
  sci.minLod = 0.0F;
  sci.maxLod = 0.0F;
  sci.borderColor = VK_BORDER_COLOR_FLOAT_TRANSPARENT_BLACK;
  VkSampler dial_sampler = VK_NULL_HANDLE;
  if (vkCreateSampler(vk_device, &sci, nullptr, &dial_sampler) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateSampler failed");
    return EXIT_FAILURE;
  }

  VkDescriptorSetLayoutBinding dsb{};
  dsb.binding = 0;
  dsb.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
  dsb.descriptorCount = 1;
  dsb.stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;
  VkDescriptorSetLayoutCreateInfo dslci{};
  dslci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
  dslci.bindingCount = 1;
  dslci.pBindings = &dsb;
  VkDescriptorSetLayout dsl = VK_NULL_HANDLE;
  if (vkCreateDescriptorSetLayout(vk_device, &dslci, nullptr, &dsl) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateDescriptorSetLayout failed");
    return EXIT_FAILURE;
  }

  VkDescriptorPoolSize dps{};
  dps.type = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
  dps.descriptorCount = 1;
  VkDescriptorPoolCreateInfo dpci{};
  dpci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
  dpci.maxSets = 1;
  dpci.poolSizeCount = 1;
  dpci.pPoolSizes = &dps;
  VkDescriptorPool dpool = VK_NULL_HANDLE;
  if (vkCreateDescriptorPool(vk_device, &dpci, nullptr, &dpool) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateDescriptorPool failed");
    return EXIT_FAILURE;
  }
  VkDescriptorSetAllocateInfo dsai{};
  dsai.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
  dsai.descriptorPool = dpool;
  dsai.descriptorSetCount = 1;
  dsai.pSetLayouts = &dsl;
  VkDescriptorSet dset = VK_NULL_HANDLE;
  if (vkAllocateDescriptorSets(vk_device, &dsai, &dset) != VK_SUCCESS) {
    drm::println(stderr, "vkAllocateDescriptorSets failed");
    return EXIT_FAILURE;
  }
  VkDescriptorImageInfo dii{};
  dii.sampler = dial_sampler;
  dii.imageView = dial_view;
  dii.imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
  VkWriteDescriptorSet wds{};
  wds.sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
  wds.dstSet = dset;
  wds.dstBinding = 0;
  wds.descriptorCount = 1;
  wds.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
  wds.pImageInfo = &dii;
  vkUpdateDescriptorSets(vk_device, 1, &wds, 0, nullptr);

  // Textured shader modules.
  VkShaderModule tex_vert = make_shader_module(vk_device, k_textured_vert_spv,
                                               sizeof(k_textured_vert_spv));
  VkShaderModule tex_frag = make_shader_module(vk_device, k_textured_frag_spv,
                                               sizeof(k_textured_frag_spv));
  if (tex_vert == VK_NULL_HANDLE || tex_frag == VK_NULL_HANDLE) {
    drm::println(stderr, "vkCreateShaderModule (textured) failed");
    return EXIT_FAILURE;
  }

  // Textured pipeline layout: descriptor set + push constants.
  VkPushConstantRange tex_pcr{};
  tex_pcr.stageFlags = VK_SHADER_STAGE_VERTEX_BIT;
  tex_pcr.offset = 0;
  tex_pcr.size = sizeof(TexturedPushConstants);
  VkPipelineLayoutCreateInfo tex_plci{};
  tex_plci.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
  tex_plci.setLayoutCount = 1;
  tex_plci.pSetLayouts = &dsl;
  tex_plci.pushConstantRangeCount = 1;
  tex_plci.pPushConstantRanges = &tex_pcr;
  VkPipelineLayout tex_pipeline_layout = VK_NULL_HANDLE;
  if (vkCreatePipelineLayout(vk_device, &tex_plci, nullptr, &tex_pipeline_layout) != VK_SUCCESS) {
    drm::println(stderr, "vkCreatePipelineLayout (textured) failed");
    return EXIT_FAILURE;
  }

  std::array<VkPipelineShaderStageCreateInfo, 2> tex_stages{};
  tex_stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  tex_stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
  tex_stages[0].module = tex_vert;
  tex_stages[0].pName = "main";
  tex_stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  tex_stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
  tex_stages[1].module = tex_frag;
  tex_stages[1].pName = "main";

  // Premultiplied-alpha blend so the dial template's alpha-0 corners
  // let the bg gradient show through.
  VkPipelineColorBlendAttachmentState tex_cba{};
  tex_cba.blendEnable = VK_TRUE;
  tex_cba.srcColorBlendFactor = VK_BLEND_FACTOR_ONE;
  tex_cba.dstColorBlendFactor = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
  tex_cba.colorBlendOp = VK_BLEND_OP_ADD;
  tex_cba.srcAlphaBlendFactor = VK_BLEND_FACTOR_ONE;
  tex_cba.dstAlphaBlendFactor = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
  tex_cba.alphaBlendOp = VK_BLEND_OP_ADD;
  tex_cba.colorWriteMask =
      VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
      VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
  VkPipelineColorBlendStateCreateInfo tex_cb{};
  tex_cb.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
  tex_cb.attachmentCount = 1;
  tex_cb.pAttachments = &tex_cba;

  VkGraphicsPipelineCreateInfo tex_gpci{};
  tex_gpci.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
  tex_gpci.stageCount = static_cast<std::uint32_t>(tex_stages.size());
  tex_gpci.pStages = tex_stages.data();
  tex_gpci.pVertexInputState = &vi;            // empty, same as bg
  tex_gpci.pInputAssemblyState = &ia;          // triangle list
  tex_gpci.pViewportState = &vp;               // same fb-sized viewport
  tex_gpci.pRasterizationState = &rs;
  tex_gpci.pMultisampleState = &ms;
  tex_gpci.pColorBlendState = &tex_cb;
  tex_gpci.layout = tex_pipeline_layout;
  tex_gpci.renderPass = render_pass;
  tex_gpci.subpass = 0;
  VkPipeline tex_pipeline = VK_NULL_HANDLE;
  if (vkCreateGraphicsPipelines(vk_device, VK_NULL_HANDLE, 1, &tex_gpci, nullptr,
                                &tex_pipeline) != VK_SUCCESS) {
    drm::println(stderr, "vkCreateGraphicsPipelines (textured) failed");
    return EXIT_FAILURE;
  }

  // Pre-computed push constants for the centered dial — the dst rect
  // doesn't change once the mode is locked.
  const TexturedPushConstants dial_pc =
      make_quad_pc(dial_x, dial_y, dial_size, dial_size, fb_w, fb_h);

  drm::PageFlip page_flip(device);
  bool flip_pending = false;
  page_flip.set_handler([&](std::uint32_t, std::uint64_t, std::uint64_t) {
    flip_pending = false;
  });

  // First commit: scene comes up with the (zero-initialized) Vulkan
  // image on PRIMARY and the (transparent) instruments dumb buffer on
  // OVERLAY. The visible result is plain black for one frame; the
  // first render loop iteration immediately overwrites it.
  if (auto r = scene->commit(DRM_MODE_PAGE_FLIP_EVENT, &page_flip); !r) {
    drm::println(stderr, "first commit: {}", r.error().message());
    return EXIT_FAILURE;
  }
  flip_pending = true;

  using clk = std::chrono::steady_clock;
  const auto t0 = clk::now();
  const auto deadline = t0 + std::chrono::seconds(args.seconds);
  std::uint64_t frames = 0;

  // Optional jitter capture, env-gated to match cluster_sim.
  const bool jitter_enabled = std::getenv("CLUSTER_SIM_FRAME_JITTER") != nullptr;
  auto last_flip = clk::now();
  double max_dt_us = 0.0;
  double sum_dt_us = 0.0;
  std::uint64_t jitter_samples = 0;

  const BgPushConstants bg_pc{static_cast<float>(fb_w), static_cast<float>(fb_h)};

  while (clk::now() < deadline && !g_quit.load(std::memory_order_relaxed)) {
    // Wait for previous flip.
    while (flip_pending && !g_quit.load(std::memory_order_relaxed)) {
      (void)page_flip.dispatch(0);
    }
    if (g_quit.load(std::memory_order_relaxed)) {
      break;
    }
    if (jitter_enabled) {
      const auto now = clk::now();
      const double dt = std::chrono::duration<double, std::micro>(now - last_flip).count();
      if (jitter_samples > 0) {
        sum_dt_us += dt;
        if (dt > max_dt_us) {
          max_dt_us = dt;
        }
      }
      last_flip = now;
      ++jitter_samples;
    }

    const double t = std::chrono::duration<double>(clk::now() - t0).count();

    vkResetCommandBuffer(cmd, 0);
    VkCommandBufferBeginInfo cbi{};
    cbi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    cbi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(cmd, &cbi);

    VkRenderPassBeginInfo rpbi{};
    rpbi.sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO;
    rpbi.renderPass = render_pass;
    rpbi.framebuffer = framebuffer;
    rpbi.renderArea.offset = {0, 0};
    rpbi.renderArea.extent = {fb_w, fb_h};
    rpbi.clearValueCount = 0;
    rpbi.pClearValues = nullptr;
    vkCmdBeginRenderPass(cmd, &rpbi, VK_SUBPASS_CONTENTS_INLINE);

    // Pass 1: bg radial gradient via full-screen triangle.
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline);
    vkCmdPushConstants(cmd, pipeline_layout, VK_SHADER_STAGE_FRAGMENT_BIT, 0, sizeof(bg_pc),
                       &bg_pc);
    vkCmdDraw(cmd, 3, 1, 0, 0);

    // Pass 2: centered dial template alpha-blended over the bg.
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, tex_pipeline);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, tex_pipeline_layout, 0, 1,
                            &dset, 0, nullptr);
    vkCmdPushConstants(cmd, tex_pipeline_layout, VK_SHADER_STAGE_VERTEX_BIT, 0, sizeof(dial_pc),
                       &dial_pc);
    vkCmdDraw(cmd, 6, 1, 0, 0);

    vkCmdEndRenderPass(cmd);
    vkEndCommandBuffer(cmd);

    VkSubmitInfo si{};
    si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    si.commandBufferCount = 1;
    si.pCommandBuffers = &cmd;
    vkQueueSubmit(queue, 1, &si, VK_NULL_HANDLE);
    vkQueueWaitIdle(queue);

    // CPU-side overlay: just the moving needle + hub. Rim/face/ticks
    // are baked into the Vulkan dial template above.
    const double speedo_norm = dial_norm_from_phase(t / k_speedo_period_s);
    if (auto m = inst_src_raw->map(drm::MapAccess::Write); m) {
      paint_needle_only(*m, dial_size, dial_size, speedo_norm);
    }

    if (auto r = scene->commit(DRM_MODE_PAGE_FLIP_EVENT | DRM_MODE_ATOMIC_NONBLOCK, &page_flip);
        !r) {
      drm::println(stderr, "commit: {}", r.error().message());
      break;
    }
    flip_pending = true;
    ++frames;
  }
  drm::println(stderr, "cluster_sim_vulkan: {} frames in {}s", frames, args.seconds);
  if (jitter_enabled && jitter_samples > 1) {
    const double mean = sum_dt_us / static_cast<double>(jitter_samples - 1);
    drm::println(stderr, "frame-jitter: frames={} mean={:.1f}us max={:.1f}us", jitter_samples,
                 mean, max_dt_us);
  }

  // Wait for any pending flip before tearing down.
  while (flip_pending) {
    (void)page_flip.dispatch(0);
  }

  scene.reset();
  vkDestroyPipeline(vk_device, tex_pipeline, nullptr);
  vkDestroyPipelineLayout(vk_device, tex_pipeline_layout, nullptr);
  vkDestroyShaderModule(vk_device, tex_frag, nullptr);
  vkDestroyShaderModule(vk_device, tex_vert, nullptr);
  vkDestroyDescriptorPool(vk_device, dpool, nullptr);
  vkDestroyDescriptorSetLayout(vk_device, dsl, nullptr);
  vkDestroySampler(vk_device, dial_sampler, nullptr);
  vkDestroyImageView(vk_device, dial_view, nullptr);
  vkFreeMemory(vk_device, dial_mem, nullptr);
  vkDestroyImage(vk_device, dial_image, nullptr);
  vkDestroyPipeline(vk_device, pipeline, nullptr);
  vkDestroyPipelineLayout(vk_device, pipeline_layout, nullptr);
  vkDestroyShaderModule(vk_device, bg_frag, nullptr);
  vkDestroyShaderModule(vk_device, bg_vert, nullptr);
  vkDestroyFramebuffer(vk_device, framebuffer, nullptr);
  vkDestroyImageView(vk_device, image_view, nullptr);
  vkDestroyRenderPass(vk_device, render_pass, nullptr);
  vkDestroyCommandPool(vk_device, cmd_pool, nullptr);
  vkFreeMemory(vk_device, vk_mem, nullptr);
  vkDestroyImage(vk_device, vk_image, nullptr);
  vkDestroyDevice(vk_device, nullptr);
  vkDestroyInstance(instance, nullptr);
  return EXIT_SUCCESS;
}
